import os
import numpy as np
import logging
import tempfile
import shutil
import subprocess
import warnings
from typing import Dict, Any, Optional, Tuple, List

# Suppress librosa file format fallback and deprecation warnings
warnings.filterwarnings("ignore", category=UserWarning, module="librosa")
warnings.filterwarnings("ignore", category=FutureWarning, module="librosa")

import ffmpeg
import cv2
from PIL import Image

from backend_ai.core.config import (
    VIDEO_EDITOR_DEFAULT_FADE_DURATION,
    VIDEO_EDITOR_MUSIC_VOLUME,
    VIDEO_EDITOR_ORIGINAL_AUDIO_VOLUME,
    VIDEO_EDITOR_PACING_SPEEDS,
)
from backend_ai.services.edl_validation_service import validate_edl
from backend_ai.core.config_loader import AGENTS_CONFIG

logger = logging.getLogger("agents.editor")


def detect_face_center(frame_rgb: np.ndarray) -> Optional[Tuple[float, float]]:
    """
    Analyzes an RGB frame using OpenCV's built-in Haar Cascade Face Detector.
    Returns normalized (x_center, y_center) of the first/most prominent face, if found.
    """
    try:
        gray = cv2.cvtColor(frame_rgb, cv2.COLOR_RGB2GRAY)
        cascade_path = cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
        face_cascade = cv2.CascadeClassifier(cascade_path)
        if face_cascade.empty():
            logger.warning("OpenCV face cascade path is empty or could not be loaded.")
            return None
            
        faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))
        if len(faces) > 0:
            # Sort by bounding box area to center on the largest/most prominent face
            faces = sorted(faces, key=lambda f: f[2] * f[3], reverse=True)
            x, y, w, h = faces[0]
            height, width = gray.shape
            x_center = (x + w / 2) / width
            y_center = (y + h / 2) / height
            return float(x_center), float(y_center)
    except Exception as e:
        logger.warning(f"Face detection failed during cropping: {e}")
    return None


class VideoEditor:
    """
    Phase 5: Assembles the final video from an Edit Decision List (EDL)
    generated by the CreativeDirector. Each timeline item is placed on a
    sequential timeline with full support for all transition types, pacing
    styles, and audio ducking.
    """

    PACING_SPEED = VIDEO_EDITOR_PACING_SPEEDS
    IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".heic", ".heif"}

    def __init__(self, clips_dir: str, output_dir: str = "data/exports"):
        self.clips_dir = clips_dir
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

        # Load from config or fallback to defaults
        editor_config = AGENTS_CONFIG.get("video_editor", {})
        self.DEFAULT_FADE_DURATION = float(editor_config.get("default_fade_duration", VIDEO_EDITOR_DEFAULT_FADE_DURATION))
        self.ORIGINAL_AUDIO_VOLUME = float(editor_config.get("original_audio_volume", 1.0))
        self.MUSIC_VOLUME = float(editor_config.get("music_volume", 0.22))
        self.MUSIC_DUCKED_VOLUME = float(editor_config.get("music_ducked_volume", 0.06))
        self.target_w = 1080
        self.target_h = 1920

        # Load video editor config for beat snapping tolerances
        self.default_beat_snap_tolerance = float(editor_config.get("default_beat_snap_tolerance", 0.2))
        self.beat_snap_tolerances = editor_config.get("beat_snap_tolerances", {})

    def _detect_non_silent_intervals(self, file_path: str, top_db: float = 30.0) -> Tuple[List[Tuple[float, float]], float]:
        """
        Uses librosa to identify non-silent intervals in the audio file.
        Returns a list of (start_time, end_time) in seconds, and total duration.
        """
        try:
            import librosa
            y, sr = librosa.load(file_path, sr=22050)
            if y.size == 0:
                return [], 0.0
            
            total_duration = y.size / sr
            intervals = librosa.effects.split(y, top_db=top_db)
            if len(intervals) == 0:
                return [], total_duration
                
            non_silent = []
            for start_idx, end_idx in intervals:
                start_t = max(0.0, float(start_idx) / sr)
                end_t = min(total_duration, float(end_idx) / sr)
                if end_t > start_t + 0.1:  # Skip fragments < 100ms
                    non_silent.append((start_t, end_t))
            return non_silent, total_duration
        except Exception as e:
            logger.warning(f"Silence detection failed for {file_path}: {e}")
            return [], 0.0

    def _get_audio_normalization_gain(self, file_path: str, target_rms: float = 0.15) -> float:
        """
        Calculates volume gain needed to normalize video audio track to target_rms.
        """
        try:
            import librosa
            y, sr = librosa.load(file_path, sr=22050)
            if y.size == 0:
                return 1.0
            rms = np.sqrt(np.mean(y ** 2))
            if rms > 1e-4:
                gain = target_rms / rms
                gain = min(max(gain, 0.1), 5.0)  # limit bounds
                if abs(gain - 1.0) > 0.05:
                    return float(gain)
        except Exception as e:
            logger.warning(f"Audio normalization calculation failed: {e}")
        return 1.0

    def _find_font(self, font_name: Optional[str] = None, weight: int = 700) -> str:
        """Finds a suitable TTF font on the system or downloads it via Google Fonts."""
        from backend_ai.utils.font_downloader import get_font_path
        try:
            return get_font_path(font_name, weight)
        except Exception as e:
            logger.warning(f"Could not resolve font '{font_name}' using downloader: {e}. Falling back to default candidates.")

        candidates = [
            "C:/Windows/Fonts/arialbd.ttf",
            "C:/Windows/Fonts/arial.ttf",
            "C:/Windows/Fonts/calibri.ttf",
            "C:/Windows/Fonts/verdana.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        ]
        for path in candidates:
            if os.path.exists(path):
                return path
        raise FileNotFoundError("No suitable font found. Please ensure Arial or Calibri is installed.")

    def _create_ken_burns_video(
        self,
        image_path: str,
        output_path: str,
        duration: float,
        target_w: int,
        target_h: int,
        direction: str = "in",
        fps: int = 30,
        face_anchor_x: float = 0.5
    ) -> None:
        """
        Generates a zoomed video from a static photo (Ken Burns effect) using Pillow.
        Pipes frames into FFmpeg to write the video file.
        """
        img = Image.open(image_path)
        if img.mode != "RGB":
            img = img.convert("RGB")
            
        orig_w, orig_h = img.size
        total_frames = int(max(1, duration * fps))
        
        base_scale = max(target_w / orig_w, target_h / orig_h)
        zoom_start, zoom_end = 1.0, 1.08
        if direction == "out":
            zoom_start, zoom_end = 1.08, 1.0
            
        cmd = [
            "ffmpeg", "-y",
            "-f", "rawvideo",
            "-pix_fmt", "rgb24",
            "-s", f"{target_w}x{target_h}",
            "-r", str(fps),
            "-i", "-",
            "-c:v", "libx264",
            "-pix_fmt", "yuv420p",
            "-an",
            output_path
        ]
        
        proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        try:
            for i in range(total_frames):
                progress = i / total_frames if total_frames > 1 else 0.0
                current_zoom = zoom_start + (zoom_end - zoom_start) * progress
                
                crop_w = int(target_w / (base_scale * current_zoom))
                crop_h = int(target_h / (base_scale * current_zoom))
                
                cx = int(face_anchor_x * orig_w - crop_w / 2)
                cx = max(0, min(orig_w - crop_w, cx))
                cy = (orig_h - crop_h) // 2
                
                cropped = img.crop((cx, cy, cx + crop_w, cy + crop_h))
                resized = cropped.resize((target_w, target_h), Image.Resampling.LANCZOS)
                
                proc.stdin.write(resized.tobytes())
        finally:
            if proc.stdin:
                proc.stdin.close()
            proc.wait()
            if proc.returncode != 0:
                stderr = proc.stderr.read().decode("utf-8") if proc.stderr else ""
                raise RuntimeError(f"Ken Burns frame piping failed: {stderr}")

    def _check_has_audio(self, file_path: str) -> bool:
        """Queries if the media file contains an audio stream."""
        try:
            result = subprocess.run(
                [
                    "ffprobe",
                    "-v", "error",
                    "-select_streams", "a",
                    "-show_entries", "stream=codec_type",
                    "-of", "csv=p=0",
                    file_path
                ],
                capture_output=True,
                text=True,
                check=True
            )
            return "audio" in result.stdout.lower()
        except Exception:
            return False

    def _get_video_frame_at_time(self, video_path: str, t_seconds: float) -> Optional[np.ndarray]:
        """Gets a frame from a video at a specific timestamp (in seconds) in RGB format."""
        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened():
            return None
        try:
            fps = float(cap.get(cv2.CAP_PROP_FPS))
            if fps <= 0:
                return None
            cap.set(cv2.CAP_PROP_POS_MSEC, t_seconds * 1000.0)
            success, frame = cap.read()
            if success:
                return cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        except Exception:
            pass
        finally:
            cap.release()
        return None

    def _escape_drawtext(self, text: str) -> str:
        """Escapes special characters for FFmpeg's drawtext filter."""
        text = text.replace("\\", "\\\\")
        text = text.replace("'", "'\\''")
        text = text.replace(":", "\\:")
        text = text.replace("%", "\\%")
        return text

    def _process_single_clip(
        self,
        clip_path: str,
        is_image: bool,
        start_in: float,
        end_in: float,
        target_duration: float,
        transition: str,
        text_overlay: str,
        pacing: str,
        music_active: bool,
        temp_path: str,
        face_anchor_x: float = 0.5,
        keep_original_audio: bool = True,
        dynamic_style: Optional[Dict[str, Any]] = None
    ) -> float:
        """
        Processes a single timeline item (trim, scale, crop, face-anchored, normalize, zoom, text-overlay)
        and exports it to a temp MP4 file. Returns the duration of the output clip.
        """
        target_w, target_h = self.target_w, self.target_h

        if is_image:
            duration = target_duration if target_duration > 0 else 3.0
            kb_direction = "in"
            self._create_ken_burns_video(
                image_path=clip_path,
                output_path=temp_path,
                duration=duration,
                target_w=target_w,
                target_h=target_h,
                direction=kb_direction,
                face_anchor_x=face_anchor_x
            )
            
            # Add silent audio track for concatenation consistency
            temp_with_audio = temp_path.replace(".mp4", "_audio.mp4")
            cmd = [
                "ffmpeg", "-y",
                "-i", temp_path,
                "-f", "lavfi",
                "-i", "anullsrc=channel_layout=stereo:sample_rate=44100",
                "-c:v", "copy",
                "-c:a", "aac",
                "-shortest",
                temp_with_audio
            ]
            subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            os.replace(temp_with_audio, temp_path)
            return duration

        # For video:
        cap = cv2.VideoCapture(clip_path)
        if not cap.isOpened():
            raise RuntimeError(f"Could not open source clip: {clip_path}")
        clip_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        clip_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        fps = float(cap.get(cv2.CAP_PROP_FPS))
        frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        orig_duration = frame_count / fps if fps > 0 else 0.0
        cap.release()
        
        has_audio = self._check_has_audio(clip_path) and keep_original_audio
        
        # Silence detection
        intervals = []
        if has_audio:
            non_silent_intervals, _ = self._detect_non_silent_intervals(clip_path)
            if non_silent_intervals:
                for ns_start, ns_end in non_silent_intervals:
                    s = max(start_in, ns_start)
                    e = min(end_in, ns_end)
                    if e > s + 0.1:
                        intervals.append((s, e))
                        
        if not intervals:
            intervals = [(start_in, min(end_in, orig_duration))]

        # Normalization and ducking volume factors
        norm_gain = self._get_audio_normalization_gain(clip_path) if has_audio else 1.0
        duck_gain = self.ORIGINAL_AUDIO_VOLUME if music_active else 1.0
        final_audio_gain = norm_gain * duck_gain

        # Horizontal crop centering using face_anchor_x (with Haar cascade fallback)
        face_x = face_anchor_x
        if face_anchor_x == 0.5:
            mid_time = (start_in + end_in) / 2
            frame_rgb = self._get_video_frame_at_time(clip_path, mid_time)
            if frame_rgb is not None:
                face_center = detect_face_center(frame_rgb)
                if face_center:
                    face_x = face_center[0]
                    logger.info(f"Smart Cropping Fallback: Haar face detected at x={face_x:.2f}")

        scale = max(target_w / clip_w, target_h / clip_h)
        new_w, new_h = int(clip_w * scale), int(clip_h * scale)
        
        crop_center_x = face_x * new_w
        x1 = max(0, min(new_w - target_w, int(crop_center_x - target_w / 2)))
        y1 = (new_h - target_h) // 2
        
        logger.info(f"Smart Cropping: Using anchor x={face_x:.2f}. Anchoring crop box horizontally to {x1}.")

        # Build FFmpeg filters
        filter_complex_parts = []
        video_output_names = []
        audio_output_names = []
        
        speed = self.PACING_SPEED.get(pacing, 1.0)
        if speed <= 0:
            speed = 1.0
            
        for idx, (s, e) in enumerate(intervals):
            v_name = f"v{idx}"
            a_name = f"a{idx}"
            
            if speed != 1.0:
                filter_complex_parts.append(
                    f"[0:v]trim=start={s}:end={e},setpts=(PTS-STARTPTS)/{speed:.2f},scale={new_w}:{new_h},crop={target_w}:{target_h}:{x1}:{y1}[{v_name}]"
                )
                if has_audio:
                    filter_complex_parts.append(
                        f"[0:a]atrim=start={s}:end={e},asetpts=PTS-STARTPTS,atempo={speed:.2f}[{a_name}]"
                    )
                else:
                    dur = (e - s) / speed
                    filter_complex_parts.append(
                        f"aevalsrc=0:d={dur:.3f},asetpts=PTS-STARTPTS[{a_name}]"
                    )
            else:
                filter_complex_parts.append(
                    f"[0:v]trim=start={s}:end={e},setpts=PTS-STARTPTS,scale={new_w}:{new_h},crop={target_w}:{target_h}:{x1}:{y1}[{v_name}]"
                )
                if has_audio:
                    filter_complex_parts.append(
                        f"[0:a]atrim=start={s}:end={e},asetpts=PTS-STARTPTS[{a_name}]"
                    )
                else:
                    dur = e - s
                    filter_complex_parts.append(
                        f"aevalsrc=0:d={dur},asetpts=PTS-STARTPTS[{a_name}]"
                    )
                
            video_output_names.append(f"[{v_name}]")
            audio_output_names.append(f"[{a_name}]")
            
        num_segments = len(intervals)
        concat_in = "".join(v + a for v, a in zip(video_output_names, audio_output_names))
        filter_complex_parts.append(
            f"{concat_in}concat=n={num_segments}:v=1:a=1[v_concat][a_concat]"
        )
        
        filter_complex_parts.append(
            f"[a_concat]volume={final_audio_gain}[a_final]"
        )
        
        video_proc_in = "[v_concat]"
        
        # Apply transitions (zoom_in / zoom_out)
        if transition == "zoom_in":
            filter_complex_parts.append(
                f"{video_proc_in}zoompan=z='1+0.04*on/30':d=1:x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':s={target_w}x{target_h}[v_zoom]"
            )
            video_proc_in = "[v_zoom]"
        elif transition == "zoom_out":
            filter_complex_parts.append(
                f"{video_proc_in}zoompan=z='1.1-0.04*on/30':d=1:x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':s={target_w}x{target_h}[v_zoom]"
            )
            video_proc_in = "[v_zoom]"
            
        # Apply text overlay
        if text_overlay:
            if dynamic_style:
                style_cfg = dynamic_style.get("text_overlay_style") or dynamic_style
            else:
                style_name = AGENTS_CONFIG.get("subtitle_agent", {}).get("caption_style", "hormozi")
                style_cfg = AGENTS_CONFIG.get("caption_styles", {}).get(style_name, {})
                
            font_name = style_cfg.get("font_name", "Arial")
            font_color = style_cfg.get("font_color", "white")
            font_size = style_cfg.get("font_size", 70)
            font_weight = style_cfg.get("font_weight", 700)
            if not dynamic_style and font_size < 50:
                font_size = 70
                
            outline_color = style_cfg.get("outline_color", "black")
            outline_width = style_cfg.get("outline_width", 2)
            if outline_color == "none":
                outline_width = 0

            font_path = self._find_font(font_name, font_weight)
            escaped_text = self._escape_drawtext(text_overlay)
            font_path_escaped = font_path.replace("\\", "/").replace(":", "\\:")
            
            drawtext_parts = [
                f"drawtext=fontfile='{font_path_escaped}'",
                f"text='{escaped_text}'",
                f"fontsize={font_size}",
                f"fontcolor={font_color}",
                "x=(w-text_w)/2",
                "y=h*0.15"
            ]
            
            # Handle shadow option dynamically
            cfg_has_shadow = style_cfg.get("has_shadow", True)
            shadow_color = style_cfg.get("shadow_color", "none")
            shadow_width = style_cfg.get("shadow_width", 0)
            if cfg_has_shadow and shadow_color != "none" and shadow_width > 0:
                drawtext_parts.append(f"shadowx={shadow_width}")
                drawtext_parts.append(f"shadowy={shadow_width}")
                drawtext_parts.append(f"shadowcolor={shadow_color}")

            if outline_width > 0:
                drawtext_parts.append(f"borderw={outline_width}")
                drawtext_parts.append(f"bordercolor={outline_color}")
                
            filter_complex_parts.append(
                f"{video_proc_in}{':'.join(drawtext_parts)}[v_text]"
            )
            video_proc_in = "[v_text]"
            
        filter_complex_parts.append(
            f"{video_proc_in}copy[v_final]"
        )
        
        filter_complex_str = ";".join(filter_complex_parts)
        
        total_intervals_duration = sum(e - s for s, e in intervals) / speed
        output_duration = target_duration if (target_duration > 0 and target_duration < total_intervals_duration) else total_intervals_duration
        
        cmd = [
            "ffmpeg", "-y",
            "-i", clip_path,
            "-filter_complex", filter_complex_str,
            "-map", "[v_final]",
            "-map", "[a_final]",
            "-c:v", "libx264",
            "-pix_fmt", "yuv420p",
            "-c:a", "aac",
            "-t", f"{output_duration:.3f}",
            temp_path
        ]
        
        logger.info(f"Running FFmpeg clip process command: {' '.join(cmd)}")
        result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if result.returncode != 0:
            logger.error(f"FFmpeg clip process failed for {clip_path}")
            logger.error(f"FFmpeg stderr: {result.stderr}")
            raise RuntimeError(f"FFmpeg clip process failed: {result.stderr}")
            
        return output_duration

    def _build_ffmpeg_concat(
        self,
        clip_paths: list[str],
        clip_durations: list[float],
        clip_has_audio: list[bool],
        transitions: list[str],
        output_path: str,
        music_path: Optional[str] = None,
        music_start_offset: float = 0.0,
        tempo: float = 0.0,
        style: str = "cinematic",
    ) -> None:
        """Assemble processed clips with FFmpeg's streaming filter graph."""
        if not clip_paths:
            raise RuntimeError("No processed clips were produced for FFmpeg assembly.")

        if not (len(clip_paths) == len(clip_durations) == len(transitions)):
            raise ValueError("FFmpeg assembly inputs must have matching lengths.")

        transition_map = {
            "crossfade": "fade",
            "fade": "fade",
            "dip_to_black": "fadeblack",
            "slide_left": "slideleft",
            "slide_right": "slideright",
        }
        temp_dir = tempfile.mkdtemp(prefix="ffmpeg_assemble_", dir=os.path.dirname(output_path))
        current_path = clip_paths[0]
        current_duration = float(clip_durations[0])

        # Calculate beat-synchronized transition duration (Task 35)
        if tempo and tempo > 0:
            beat_duration = 60.0 / tempo
            style_lower = style.lower() if style else ""
            if any(s in style_lower for s in ["fast", "energy", "ramp", "action", "travel"]):
                beat_fraction = 0.5
            else:
                beat_fraction = 1.0
            sync_fade_duration = beat_duration * beat_fraction
            # Clamp to a natural range
            sync_fade_duration = max(0.1, min(1.0, sync_fade_duration))
            logger.info(
                f"Beat sync transition: tempo={tempo} BPM, beat_dur={beat_duration:.3f}s, "
                f"fraction={beat_fraction}, sync_dur={sync_fade_duration:.3f}s"
            )
        else:
            sync_fade_duration = self.DEFAULT_FADE_DURATION

        try:
            for idx in range(1, len(clip_paths)):
                transition = (transitions[idx] or "none").lower()
                next_path = clip_paths[idx]
                next_duration = float(clip_durations[idx])
                stage_path = os.path.join(temp_dir, f"stage_{idx:03d}.mp4")

                current_input = ffmpeg.input(current_path)
                next_input = ffmpeg.input(next_path)
                target_fps = 30
                cur_video_norm = current_input.video.filter('fps', fps=target_fps).filter('settb', 'AVTB')
                next_video_norm = next_input.video.filter('fps', fps=target_fps).filter('settb', 'AVTB')

                if transition in transition_map:
                    fade_dur = min(sync_fade_duration, current_duration / 2, next_duration / 2)
                    if fade_dur > 0:
                        offset = max(0.0, current_duration - fade_dur)
                        video_stream = ffmpeg.filter(
                            [cur_video_norm, next_video_norm],
                            "xfade",
                            transition=transition_map[transition],
                            duration=fade_dur,
                            offset=offset,
                        )

                        if current_input.audio is not None and next_input.audio is not None:
                            audio_stream = ffmpeg.filter(
                                [current_input.audio, next_input.audio],
                                "acrossfade",
                                d=fade_dur,
                            )
                            stream = ffmpeg.output(
                                video_stream,
                                audio_stream,
                                stage_path,
                                vcodec="libx264",
                                acodec="aac",
                                pix_fmt="yuv420p",
                                movflags="+faststart",
                            )
                        else:
                            stream = ffmpeg.output(
                                video_stream,
                                stage_path,
                                vcodec="libx264",
                                pix_fmt="yuv420p",
                                movflags="+faststart",
                            )

                        try:
                            stream.overwrite_output().run(capture_stdout=True, capture_stderr=True)
                        except ffmpeg.Error as exc:
                            stderr = exc.stderr.decode("utf-8", errors="replace") if isinstance(exc.stderr, bytes) else str(exc.stderr)
                            raise RuntimeError(f"FFmpeg transition assembly failed: {stderr[-2000:]}") from exc

                        current_path = stage_path
                        current_duration = current_duration + next_duration - fade_dur
                        continue

                if current_input.audio is not None and next_input.audio is not None:
                    concat_node = ffmpeg.concat(
                        current_input.video,
                        next_input.video,
                        n=2,
                        v=1,
                        a=0,
                    )
                    video_stream = concat_node.node.stream("v")
                    audio_node = ffmpeg.concat(
                        current_input.audio,
                        next_input.audio,
                        n=2,
                        v=0,
                        a=1,
                    )
                    audio_stream = audio_node.node.stream("a")
                    stream = ffmpeg.output(
                        video_stream,
                        audio_stream,
                        stage_path,
                        vcodec="libx264",
                        acodec="aac",
                        pix_fmt="yuv420p",
                        movflags="+faststart",
                    )
                else:
                    concat_node = ffmpeg.concat(
                        current_input.video,
                        next_input.video,
                        n=2,
                        v=1,
                        a=0,
                    )
                    stream = ffmpeg.output(
                        concat_node.node.stream("v"),
                        stage_path,
                        vcodec="libx264",
                        pix_fmt="yuv420p",
                        movflags="+faststart",
                    )

                try:
                    stream.overwrite_output().run(capture_stdout=True, capture_stderr=True)
                except ffmpeg.Error as exc:
                    stderr = exc.stderr.decode("utf-8", errors="replace") if isinstance(exc.stderr, bytes) else str(exc.stderr)
                    raise RuntimeError(f"FFmpeg assembly failed: {stderr[-2000:]}") from exc

                current_path = stage_path
                current_duration += next_duration

            output_args = {
                "vcodec": "libx264",
                "pix_fmt": "yuv420p",
                "movflags": "+faststart",
            }

            # Calculate dynamic audio ducking intervals (Task 34)
            active_intervals = []
            accumulated = 0.0
            for idx in range(len(clip_paths)):
                dur = clip_durations[idx]
                has_aud = clip_has_audio[idx]
                
                # Check transition overlap for correct timing
                transition_term = (transitions[idx] or "none").lower()
                fade_overlap = 0.0
                if idx > 0 and transition_term in transition_map:
                    prev_dur = clip_durations[idx - 1]
                    fade_overlap = min(sync_fade_duration, prev_dur / 2, dur / 2)
                
                if idx > 0:
                    accumulated -= fade_overlap
                    
                if has_aud:
                    active_intervals.append((accumulated, accumulated + dur))
                    
                accumulated += dur

            final_input = ffmpeg.input(current_path)
            if music_path and os.path.exists(music_path):
                music_input = ffmpeg.input(music_path, stream_loop=-1)
                music_audio = music_input.audio.filter(
                    "atrim",
                    start=max(0.0, music_start_offset),
                    duration=current_duration,
                ).filter("asetpts", "PTS-STARTPTS")

                # Apply dynamic audio ducking (Task 34)
                if active_intervals:
                    duck_conditions = []
                    for start, end in active_intervals:
                        duck_conditions.append(f"between(t,{start:.3f},{end:.3f})")
                    cond_str = "+".join(duck_conditions)
                    volume_expr = f"if({cond_str}, {self.MUSIC_DUCKED_VOLUME}, {self.MUSIC_VOLUME})"
                    logger.info(f"Dynamic Audio Ducking active intervals count: {len(active_intervals)}")
                    logger.debug(f"Volume filter expression: {volume_expr}")
                else:
                    volume_expr = f"{self.MUSIC_VOLUME}"
                    logger.info("No active audio clips detected. Background music volume constant.")

                music_audio = music_audio.filter("volume", volume_expr, eval="frame")

                fade_out_start = max(0.0, current_duration - 1.5)
                music_audio = music_audio.filter("afade", t="out", st=fade_out_start, d=1.5)

                if final_input.audio is not None:
                    mixed_audio = ffmpeg.filter(
                        [final_input.audio, music_audio],
                        "amix",
                        inputs=2,
                        duration="first",
                        dropout_transition=0,
                    )
                else:
                    mixed_audio = music_audio

                stream = ffmpeg.output(final_input.video, mixed_audio, output_path, acodec="aac", **output_args)
            elif final_input.audio is not None:
                stream = ffmpeg.output(final_input.video, final_input.audio, output_path, acodec="aac", **output_args)
            else:
                stream = ffmpeg.output(final_input.video, output_path, **output_args)

            try:
                stream.overwrite_output().run(capture_stdout=True, capture_stderr=True)
            except ffmpeg.Error as exc:
                stderr = exc.stderr.decode("utf-8", errors="replace") if isinstance(exc.stderr, bytes) else str(exc.stderr)
                raise RuntimeError(f"FFmpeg assembly failed: {stderr[-2000:]}") from exc
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)

    def _enforce_final_duration(self, file_path: str, target_duration: float) -> None:
        if target_duration <= 0:
            return
            
        cap = cv2.VideoCapture(file_path)
        if not cap.isOpened():
            return
        fps = cap.get(cv2.CAP_PROP_FPS)
        frame_count = cap.get(cv2.CAP_PROP_FRAME_COUNT)
        actual_duration = frame_count / fps if fps > 0 else 0.0
        cap.release()
        
        if abs(actual_duration - target_duration) < 0.1:
            return
            
        temp_output = file_path.replace(".mp4", "_duration_enforced.mp4")
        if actual_duration > target_duration:
            logger.info(f"Trimming final video: {actual_duration:.2f}s -> target {target_duration:.2f}s")
            cmd = [
                "ffmpeg", "-y",
                "-i", file_path,
                "-t", f"{target_duration:.3f}",
                "-c", "copy",
                temp_output
            ]
            subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            os.replace(temp_output, file_path)
        else:
            pad_duration = target_duration - actual_duration
            logger.info(f"Padding final video: {actual_duration:.2f}s -> target {target_duration:.2f}s (padding of {pad_duration:.2f}s)")
            
            black_temp = tempfile.mktemp(suffix=".mp4", dir=os.path.dirname(file_path))
            cmd_black = [
                "ffmpeg", "-y",
                "-f", "lavfi", "-i", f"color=c=black:s={self.target_w}x{self.target_h}:r=30:d={pad_duration:.3f}",
                "-f", "lavfi", "-i", f"anullsrc=channel_layout=stereo:sample_rate=44100:d={pad_duration:.3f}",
                "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac",
                black_temp
            ]
            subprocess.run(cmd_black, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            
            concat_list = tempfile.mktemp(suffix=".txt", dir=os.path.dirname(file_path))
            with open(concat_list, "w") as f:
                p1 = os.path.abspath(file_path).replace("\\", "/")
                p2 = os.path.abspath(black_temp).replace("\\", "/")
                f.write(f"file '{p1}'\n")
                f.write(f"file '{p2}'\n")
                
            cmd_concat = [
                "ffmpeg", "-y",
                "-f", "concat",
                "-safe", "0",
                "-i", concat_list,
                "-c", "copy",
                temp_output
            ]
            subprocess.run(cmd_concat, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            
            os.remove(concat_list)
            os.remove(black_temp)
            os.replace(temp_output, file_path)

    def _cleanup_temp_files(self, temp_files: list[str], temp_dir: Optional[str] = None) -> None:
        for path in temp_files:
            if not path:
                continue
            try:
                if os.path.exists(path):
                    os.unlink(path)
            except Exception as e:
                logger.warning(f"Failed to delete temp file {path}: {e}")

        if temp_dir and os.path.isdir(temp_dir):
            try:
                shutil.rmtree(temp_dir, ignore_errors=True)
            except Exception:
                pass

    def render(
        self,
        edl: Dict[str, Any],
        music_path: Optional[str] = None,
        output_filename: str = "shortify_output.mp4",
        aspect_ratio: str = "9:16",
        rhythm_data: Optional[Dict[str, Any]] = None,
        clip_scores: Optional[Dict[str, Any]] = None,
        dynamic_style: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Renders the final video from an EDL produced by CreativeDirector.
        """
        self.skipped_clips = []
        validated_edl = validate_edl(edl, self.clips_dir)
        edl = validated_edl.model_dump(mode="json")

        timeline = edl.get("timeline", [])
        if not timeline:
            raise ValueError("EDL timeline is empty. Nothing to render.")

        timeline.sort(key=lambda x: float(x.get("timeline_start", 0.0)))

        dimensions_map = {
            "9:16": (1080, 1920),
            "16:9": (1920, 1080),
            "1:1": (1080, 1080),
        }
        self.target_w, self.target_h = dimensions_map.get(aspect_ratio, (1080, 1920))

        title = edl.get("title", "Untitled")
        logger.info(f"Rendering '{title}' | aspect={aspect_ratio} | dims={self.target_w}x{self.target_h} | segments={len(timeline)}")

        processed_temp_files = []
        processed_durations = []
        transitions = []
        processed_has_audio = []
        temp_dir = tempfile.mkdtemp(prefix="video_editor_", dir=self.output_dir)
        
        beat_times = rhythm_data.get("beat_times", []) if rhythm_data else []
        accumulated_time = 0.0

        output_path = os.path.join(self.output_dir, output_filename)

        try:
            for i, item in enumerate(timeline):
                clip_name = item.get("clip_name", "")
                start_in = float(item.get("start_in_clip", 0.0))
                end_in = float(item.get("end_in_clip", 0.0))
                tl_start = float(item.get("timeline_start", 0.0))
                tl_end = float(item.get("timeline_end", end_in - start_in))
                transition = item.get("transition", "none").lower()
                details = item.get("details", {})
                pacing = details.get("pacing_style", "jump-cut").lower()

                # Snapping to beats
                raw_duration = tl_end - tl_start
                target_duration = raw_duration

                if beat_times:
                    raw_tl_end = accumulated_time + raw_duration
                    nearest_beat = min(beat_times, key=lambda b: abs(b - raw_tl_end))
                    tolerance = float(self.beat_snap_tolerances.get(pacing, self.default_beat_snap_tolerance))
                    if abs(nearest_beat - raw_tl_end) <= tolerance:
                        target_duration = max(0.1, nearest_beat - accumulated_time)
                        logger.info(
                            f"Beat sync: snapping clip end {raw_tl_end:.2f}s -> beat {nearest_beat:.2f}s "
                            f"(dur {raw_duration:.2f}s -> {target_duration:.2f}s, tolerance={tolerance}s)"
                        )

                accumulated_time += target_duration

                # Virtual clip extraction
                virtual_start = 0.0
                virtual_end = None
                source_filename = clip_name

                if ":" in clip_name:
                    parts = clip_name.split(":", 2)
                    if len(parts) == 3:
                        try:
                            source_filename = parts[0]
                            virtual_start = float(parts[1])
                            virtual_end = float(parts[2])
                        except ValueError:
                            pass

                clip_path = os.path.join(self.clips_dir, source_filename)
                if not os.path.exists(clip_path):
                    logger.warning(f"Clip not found, skipping: {clip_name}")
                    self.skipped_clips.append(clip_name)
                    continue

                ext = os.path.splitext(clip_path)[1].lower()
                is_image = ext in self.IMAGE_EXTENSIONS

                # Set subclip bounds
                if is_image:
                    actual_start = 0.0
                    actual_end = target_duration
                else:
                    if virtual_end is not None:
                        actual_start = virtual_start + start_in
                        actual_end = min(virtual_start + end_in, virtual_end)
                    else:
                        actual_start = start_in
                        actual_end = end_in

                temp_clip_path = os.path.join(temp_dir, f"clip_{len(processed_temp_files):03d}.mp4")
                
                try:
                    logger.info(f"Processing clip: {clip_name} -> {temp_clip_path}")
                    
                    face_anchor_x = 0.5
                    if clip_scores and source_filename in clip_scores:
                        face_anchor_x = clip_scores[source_filename].get("face_anchor_x", 0.5)

                    keep_aud = details.get("keep_original_audio", True)
                    has_aud = (not is_image) and self._check_has_audio(clip_path) and keep_aud

                    processed_dur = self._process_single_clip(
                        clip_path=clip_path,
                        is_image=is_image,
                        start_in=actual_start,
                        end_in=actual_end,
                        target_duration=target_duration,
                        transition=transition,
                        text_overlay=item.get("text_overlay", "").strip(),
                        pacing=pacing,
                        music_active=bool(music_path and os.path.exists(music_path)),
                        temp_path=temp_clip_path,
                        face_anchor_x=face_anchor_x,
                        keep_original_audio=keep_aud,
                        dynamic_style=dynamic_style
                    )
                    
                    processed_temp_files.append(temp_clip_path)
                    processed_durations.append(processed_dur)
                    transitions.append(transition)
                    processed_has_audio.append(has_aud)

                    media_type_label = "photo" if is_image else "video"
                    logger.info(
                        f"[{i+1}/{len(timeline)}] [{media_type_label}] {clip_name} | "
                        f"dur={processed_dur:.2f}s | transition={transition} | pacing={pacing}"
                    )
                except Exception as e:
                    logger.error(f"Failed to process clip {clip_name} at index {i}: {e}", exc_info=True)
                    self.skipped_clips.append(clip_name)
                    continue

            if not processed_temp_files:
                raise RuntimeError("No valid clips were processed. Check clips directory and EDL.")

            self._build_ffmpeg_concat(
                clip_paths=processed_temp_files,
                clip_durations=processed_durations,
                clip_has_audio=processed_has_audio,
                transitions=transitions,
                output_path=output_path,
                music_path=music_path,
                music_start_offset=float(edl.get("music_start_offset", 0.0)),
                tempo=rhythm_data.get("tempo", 0.0) if rhythm_data else 0.0,
                style=edl.get("style", "cinematic"),
            )

            # Enforce exact target duration (trim/pad final video)
            target_duration = float(edl.get("total_duration", 0.0))
            if target_duration > 0:
                self._enforce_final_duration(output_path, target_duration)

            logger.info(f"Render complete! Output: {output_path}")
            return output_path
        finally:
            self._cleanup_temp_files(processed_temp_files, temp_dir=temp_dir)


if __name__ == "__main__":
    logger.info("VideoEditor module loaded successfully.")
