import os
from typing import Dict, Any, Optional

from moviepy import (
    VideoFileClip,
    AudioFileClip,
    CompositeVideoClip,
    CompositeAudioClip,
    concatenate_videoclips,
)
from moviepy.audio.fx import MultiplyVolume
from moviepy.video.fx import CrossFadeIn, Resize


class VideoEditor:
    """
    Phase 5: Assembles the final video from an Edit Decision List (EDL)
    generated by the CreativeDirector. Each timeline item is placed at the
    exact start/end position specified by the director, with full support
    for transitions, pacing styles, and audio ducking.
    """

    ORIGINAL_AUDIO_VOLUME = 0.1   # Duck original clip audio when music plays
    MUSIC_VOLUME = 0.9
    DEFAULT_FADE_DURATION = 0.3

    # Speed multipliers for pacing styles defined by the director
    PACING_SPEED = {
        "speed-ramp": 1.5,       # faster cut
        "jump-cut": 1.0,         # no speed change, handled by clip selection
        "cinematic-slow": 0.75,  # slower, more dramatic
    }

    def __init__(self, clips_dir: str, output_dir: str = "data/exports"):
        self.clips_dir = clips_dir
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def render(
        self,
        edl: Dict[str, Any],
        music_path: Optional[str] = None,
        output_filename: str = "shortify_output.mp4"
    ) -> str:
        """
        Renders the final video from an EDL produced by CreativeDirector.

        The director's EDL specifies:
          - clip_name, start_in_clip, end_in_clip  (what to take from source)
          - timeline_start, timeline_end            (where it lands on the timeline)
          - transition                              (how to join to the previous clip)
          - details.pacing_style                   (speed-ramp / jump-cut / cinematic-slow)
        """
        timeline = edl.get("timeline", [])
        if not timeline:
            raise ValueError("EDL timeline is empty. Nothing to render.")

        title = edl.get("title", "Untitled")
        print(f"Rendering '{title}' - {len(timeline)} director-specified segments...")

        processed_clips = []

        for i, item in enumerate(timeline):
            clip_name   = item.get("clip_name", "")
            start_in    = float(item.get("start_in_clip", 0.0))
            end_in      = float(item.get("end_in_clip", 0.0))
            tl_start    = float(item.get("timeline_start", 0.0))
            tl_end      = float(item.get("timeline_end", end_in - start_in))
            transition  = item.get("transition", "none").lower()
            details     = item.get("details", {})
            pacing      = details.get("pacing_style", "jump-cut").lower()

            clip_path = os.path.join(self.clips_dir, clip_name)
            if not os.path.exists(clip_path):
                print(f"  Warning: clip not found, skipping -> {clip_name}")
                continue

            # 1. Load & trim from source
            raw = VideoFileClip(clip_path)
            safe_end = min(end_in, raw.duration)
            clip = raw.subclipped(start_in, safe_end)

            # 2. Apply pacing style (speed multiplier)
            speed = self.PACING_SPEED.get(pacing, 1.0)
            if speed != 1.0:
                clip = clip.with_effects([
                    # multiply_speed is the MoviePy 2.0 way to change speed
                    __import__(
                        "moviepy.video.fx",
                        fromlist=["MultiplySpeed"]
                    ).MultiplySpeed(speed)
                ])

            # 3. If the director specified a target duration on the timeline,
            #    trim or extend the clip to match exactly.
            target_duration = round(tl_end - tl_start, 4)
            if target_duration > 0 and abs(clip.duration - target_duration) > 0.05:
                clip = clip.with_duration(min(target_duration, clip.duration))

            # 4. Apply transitions
            if transition in ("fade", "crossfade") and i > 0:
                fade_dur = min(self.DEFAULT_FADE_DURATION, clip.duration / 2)
                clip = clip.with_effects([CrossFadeIn(fade_dur)])

            if transition == "zoom_in":
                clip = clip.with_effects([Resize(lambda t: 1 + 0.03 * t)])

            # 5. Duck original audio
            if clip.audio is not None:
                clip = clip.with_audio(
                    clip.audio.with_effects([MultiplyVolume(self.ORIGINAL_AUDIO_VOLUME)])
                )

            processed_clips.append(clip)
            print(
                f"  [{i+1}/{len(timeline)}] {clip_name} | "
                f"src {start_in:.2f}s-{safe_end:.2f}s | "
                f"timeline {tl_start:.2f}s-{tl_end:.2f}s | "
                f"pacing: {pacing} | transition: {transition}"
            )

        if not processed_clips:
            raise RuntimeError("No valid clips were processed. Check clips directory and EDL.")

        # 6. Concatenate in director order (timeline positions already encoded
        #    via clip durations that match timeline_start -> timeline_end gaps)
        print("Concatenating clips per director timeline...")
        final_video = concatenate_videoclips(processed_clips, method="compose")

        # 7. Mix background music
        if music_path and os.path.exists(music_path):
            print(f"Mixing background music: {music_path}")
            music = AudioFileClip(music_path).subclipped(0, final_video.duration)
            music = music.with_effects([MultiplyVolume(self.MUSIC_VOLUME)])
            if final_video.audio:
                mixed = CompositeAudioClip([final_video.audio, music])
            else:
                mixed = music
            final_video = final_video.with_audio(mixed)

        # 8. Write output
        output_path = os.path.join(self.output_dir, output_filename)
        print(f"Writing final video -> {output_path}")
        final_video.write_videofile(
            output_path,
            codec="libx264",
            audio_codec="aac",
            temp_audiofile=os.path.join(self.output_dir, "temp_audio.m4a"),
            remove_temp=True,
            logger="bar",
        )

        for clip in processed_clips:
            clip.close()
        final_video.close()

        print(f"Render complete! Output: {output_path}")
        return output_path


if __name__ == "__main__":
    print("VideoEditor module loaded successfully.")
