import os
import numpy as np
import logging
import tempfile
import shutil
import subprocess
import warnings
from typing import Dict, Any, Optional, Tuple, List

# Suppress librosa file format fallback and deprecation warnings
warnings.filterwarnings("ignore", category=UserWarning, module="librosa")
warnings.filterwarnings("ignore", category=FutureWarning, module="librosa")

import ffmpeg
import cv2
from PIL import Image

from backend_ai.core.config import (
    VIDEO_EDITOR_DEFAULT_FADE_DURATION,
    VIDEO_EDITOR_MUSIC_VOLUME,
    VIDEO_EDITOR_ORIGINAL_AUDIO_VOLUME,
    VIDEO_EDITOR_PACING_SPEEDS,
)
from backend_ai.services.edl_validation_service import validate_edl
from backend_ai.core.config_loader import AGENTS_CONFIG

logger = logging.getLogger("agents.editor")


def detect_face_center(frame_rgb: np.ndarray) -> Optional[Tuple[float, float]]:
    """
    Analyzes an RGB frame using OpenCV's built-in Haar Cascade Face Detector.
    Returns normalized (x_center, y_center) of the first/most prominent face, if found.
    """
    try:
        gray = cv2.cvtColor(frame_rgb, cv2.COLOR_RGB2GRAY)
        cascade_path = cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
        face_cascade = cv2.CascadeClassifier(cascade_path)
        if face_cascade.empty():
            logger.warning("OpenCV face cascade path is empty or could not be loaded.")
            return None
            
        faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))
        if len(faces) > 0:
            # Sort by bounding box area to center on the largest/most prominent face
            faces = sorted(faces, key=lambda f: f[2] * f[3], reverse=True)
            x, y, w, h = faces[0]
            height, width = gray.shape
            x_center = (x + w / 2) / width
            y_center = (y + h / 2) / height
            return float(x_center), float(y_center)
    except Exception as e:
        logger.warning(f"Face detection failed during cropping: {e}")
    return None


class VideoEditor:
    """
    Phase 5: Assembles the final video from an Edit Decision List (EDL)
    generated by the CreativeDirector. Each timeline item is placed on a
    sequential timeline with full support for all transition types, pacing
    styles, and audio ducking.
    """

    PACING_SPEED = VIDEO_EDITOR_PACING_SPEEDS
    IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".heic", ".heif"}

    def __init__(self, clips_dir: str, output_dir: str = "data/exports"):
        self.clips_dir = clips_dir
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

        # Load from config or fallback to defaults
        editor_config = AGENTS_CONFIG.get("video_editor", {})
        self.DEFAULT_FADE_DURATION = float(editor_config.get("default_fade_duration", VIDEO_EDITOR_DEFAULT_FADE_DURATION))
        self.ORIGINAL_AUDIO_VOLUME = float(editor_config.get("original_audio_volume", 1.0))
        self.MUSIC_VOLUME = float(editor_config.get("music_volume", 0.22))
        self.MUSIC_DUCKED_VOLUME = float(editor_config.get("music_ducked_volume", 0.06))
        self.target_w = 1080
        self.target_h = 1920

        # Load video editor config for beat snapping tolerances
        self.default_beat_snap_tolerance = float(editor_config.get("default_beat_snap_tolerance", 0.2))
        self.beat_snap_tolerances = editor_config.get("beat_snap_tolerances", {})

    def _detect_non_silent_intervals(self, file_path: str, top_db: float = 30.0) -> Tuple[List[Tuple[float, float]], float]:
        """
        Uses librosa to identify non-silent intervals in the audio file.
        Returns a list of (start_time, end_time) in seconds, and total duration.
        """
        try:
            import librosa
            y, sr = librosa.load(file_path, sr=22050)
            if y.size == 0:
                return [], 0.0
            
            total_duration = y.size / sr
            intervals = librosa.effects.split(y, top_db=top_db)
            if len(intervals) == 0:
                return [], total_duration
                
            non_silent = []
            for start_idx, end_idx in intervals:
                start_t = max(0.0, float(start_idx) / sr)
                end_t = min(total_duration, float(end_idx) / sr)
                if end_t > start_t + 0.1:  # Skip fragments < 100ms
                    non_silent.append((start_t, end_t))
            return non_silent, total_duration
        except Exception as e:
            logger.warning(f"Silence detection failed for {file_path}: {e}")
            return [], 0.0

    def _get_audio_normalization_gain(self, file_path: str, target_rms: float = 0.15) -> float:
        """
        Calculates volume gain needed to normalize video audio track to target_rms.
        """
        try:
            import librosa
            y, sr = librosa.load(file_path, sr=22050)
            if y.size == 0:
                return 1.0
            rms = np.sqrt(np.mean(y ** 2))
            if rms > 1e-4:
                gain = target_rms / rms
                gain = min(max(gain, 0.1), 5.0)  # limit bounds
                if abs(gain - 1.0) > 0.05:
                    return float(gain)
        except Exception as e:
            logger.warning(f"Audio normalization calculation failed: {e}")
        return 1.0

    def _find_font(self, font_name: Optional[str] = None, weight: int = 700) -> str:
        """Finds a suitable TTF font on the system or downloads it via Google Fonts."""
        from backend_ai.utils.font_downloader import get_font_path
        try:
            return get_font_path(font_name, weight)
        except Exception as e:
            logger.warning(f"Could not resolve font '{font_name}' using downloader: {e}. Falling back to default candidates.")

        candidates = [
            "C:/Windows/Fonts/arialbd.ttf",
            "C:/Windows/Fonts/arial.ttf",
            "C:/Windows/Fonts/calibri.ttf",
            "C:/Windows/Fonts/verdana.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        ]
        for path in candidates:
            if os.path.exists(path):
                return path
        raise FileNotFoundError("No suitable font found. Please ensure Arial or Calibri is installed.")

    def _create_ken_burns_video(
        self,
        image_path: str,
        output_path: str,
        duration: float,
        target_w: int,
        target_h: int,
        direction: str = "in",
        fps: int = 30,
        face_anchor_x: float = 0.5
    ) -> None:
        """
        Generates a zoomed video from a static photo (Ken Burns effect) using Pillow.
        Pipes frames into FFmpeg to write the video file.
        """
        img = Image.open(image_path)
        if img.mode != "RGB":
            img = img.convert("RGB")
            
        orig_w, orig_h = img.size
        total_frames = int(max(1, duration * fps))
        
        base_scale = max(target_w / orig_w, target_h / orig_h)
        zoom_start, zoom_end = 1.0, 1.08
        if direction == "out":
            zoom_start, zoom_end = 1.08, 1.0
            
        cmd = [
            "ffmpeg", "-y",
            "-f", "rawvideo",
            "-pix_fmt", "rgb24",
            "-s", f"{target_w}x{target_h}",
            "-r", str(fps),
            "-i", "-",
            "-c:v", "libx264",
            "-pix_fmt", "yuv420p",
            "-an",
            output_path
        ]
        
        proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        try:
            for i in range(total_frames):
                progress = i / total_frames if total_frames > 1 else 0.0
                current_zoom = zoom_start + (zoom_end - zoom_start) * progress
                
                crop_w = int(target_w / (base_scale * current_zoom))
                crop_h = int(target_h / (base_scale * current_zoom))
                
                cx = int(face_anchor_x * orig_w - crop_w / 2)
                cx = max(0, min(orig_w - crop_w, cx))
                cy = (orig_h - crop_h) // 2
                
                cropped = img.crop((cx, cy, cx + crop_w, cy + crop_h))
                resized = cropped.resize((target_w, target_h), Image.Resampling.LANCZOS)
                
                proc.stdin.write(resized.tobytes())
        finally:
            if proc.stdin:
                proc.stdin.close()
            proc.wait()
            if proc.returncode != 0:
                stderr = proc.stderr.read().decode("utf-8") if proc.stderr else ""
                raise RuntimeError(f"Ken Burns frame piping failed: {stderr}")

    def _check_has_audio(self, file_path: str) -> bool:
        """Queries if the media file contains an audio stream."""
        try:
            result = subprocess.run(
                [
                    "ffprobe",
                    "-v", "error",
                    "-select_streams", "a",
                    "-show_entries", "stream=codec_type",
                    "-of", "csv=p=0",
                    file_path
                ],
                capture_output=True,
                text=True,
                check=True,
                stdin=subprocess.DEVNULL
            )
            return "audio" in result.stdout.lower()
        except Exception:
            return False

    def _get_video_frame_at_time(self, video_path: str, t_seconds: float) -> Optional[np.ndarray]:
        """Gets a frame from a video at a specific timestamp (in seconds) in RGB format."""
        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened():
            return None
        try:
            fps = float(cap.get(cv2.CAP_PROP_FPS))
            if fps <= 0:
                return None
            cap.set(cv2.CAP_PROP_POS_MSEC, t_seconds * 1000.0)
            success, frame = cap.read()
            if success:
                return cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        except Exception:
            pass
        finally:
            cap.release()
        return None

    def _escape_drawtext(self, text: str) -> str:
        """Escapes special characters for FFmpeg's drawtext filter."""
        text = text.replace("\\", "\\\\")
        text = text.replace("'", "'\\''")
        text = text.replace(":", "\\:")
        text = text.replace("%", "\\%")
        return text

    def _process_single_clip(
        self,
        clip_path: str,
        is_image: bool,
        start_in: float,
        end_in: float,
        target_duration: float,
        transition: str,
        text_overlay: str,
        pacing: str,
        music_active: bool,
        temp_path: str,
        face_anchor_x: float = 0.5,
        keep_original_audio: bool = True,
        dynamic_style: Optional[Dict[str, Any]] = None,
        sticker_path: Optional[str] = None,
        sticker_position: Optional[str] = "bottom-center",
        effect_path: Optional[str] = None,
        color_grade: Optional[Dict[str, Any]] = None,
        clip_effect: Optional[Dict[str, Any]] = None,
        speed_preset: Optional[str] = None,
        speed_keyframes: Optional[List[Tuple[float, float]]] = None,
        reverse: bool = False,
        stabilize: bool = False,
        stabilize_strength: float = 0.5,
        text_preset: Optional[str] = None,
        text_animation: Optional[str] = None,
        sticker_animation: Optional[str] = None,
        original_audio_volume: Optional[float] = None
    ) -> float:
        """
        Processes a single timeline item (trim, scale, crop, face-anchored, normalize, zoom, text-overlay)
        and exports it to a temp MP4 file. Returns the duration of the output clip.
        """
        target_w, target_h = self.target_w, self.target_h
        temp_kb = None
        temp_stabilized = None

        try:
            effects_enabled = os.getenv("EFFECTS_ENABLED", "true").strip().lower() == "true"
            if not effects_enabled:
                effect_path = None

            # Move stabilization here to process before slicing
            stabilize_trf_path = None
            if stabilize and not is_image:
                dur = end_in - start_in
                if dur >= 0.5:
                    from backend_ai.effects.stabilization import stabilize_clip
                    try:
                        stabilize_trf_path = stabilize_clip(
                            clip_path=clip_path,
                            start=start_in,
                            end=end_in,
                            temp_dir=os.path.dirname(temp_path),
                            strength=stabilize_strength
                        )
                        temp_stabilized = temp_path.replace(".mp4", "_stabilized_temp.mp4")
                        trf_path_escaped = stabilize_trf_path.replace("\\", "/").replace(":", "\\:")
                        
                        cmd = [
                            "ffmpeg", "-y", "-nostdin",
                            "-ss", f"{start_in:.3f}",
                            "-to", f"{end_in:.3f}",
                            "-i", clip_path,
                            "-vf", f"fps=fps=30,vidstabtransform=input={trf_path_escaped}:smoothing=15:optzoom=1",
                            "-map", "0:v",
                            "-map", "0:a?",
                            "-c:v", "libx264",
                            "-pix_fmt", "yuv420p",
                            "-c:a", "aac",
                            "-ar", "44100",
                            "-ac", "2",
                            temp_stabilized
                        ]
                        logger.info(f"Running stabilization render pass: {' '.join(cmd)}")
                        result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, stdin=subprocess.DEVNULL, timeout=180)
                        if result.returncode != 0:
                            logger.error(f"Stabilization render pass failed: {result.stderr}")
                            raise RuntimeError(f"FFmpeg stabilization render failed: {result.stderr}")
                        
                        clip_path = temp_stabilized
                        start_in = 0.0
                        end_in = dur
                        stabilize_trf_path = None
                    except Exception as e:
                        logger.warning(f"Stabilization failed: {e}. Proceeding without stabilization.")
                        stabilize_trf_path = None
                        if temp_stabilized and os.path.exists(temp_stabilized):
                            try:
                                os.remove(temp_stabilized)
                            except Exception:
                                pass
                            temp_stabilized = None

            if is_image:
                duration = target_duration if target_duration > 0 else 3.0
                kb_direction = "in"
                temp_kb = temp_path.replace(".mp4", "_kb_temp.mp4")
                self._create_ken_burns_video(
                    image_path=clip_path,
                    output_path=temp_kb,
                    duration=duration,
                    target_w=target_w,
                    target_h=target_h,
                    direction=kb_direction,
                    face_anchor_x=face_anchor_x
                )
                clip_path = temp_kb

            # Process clip (unified video and Ken Burns source)
            cap = cv2.VideoCapture(clip_path)
            if not cap.isOpened():
                raise RuntimeError(f"Could not open source clip: {clip_path}")
            clip_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
            clip_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
            fps = float(cap.get(cv2.CAP_PROP_FPS))
            frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
            orig_duration = frame_count / fps if fps > 0 else 0.0
            cap.release()
            
            has_audio = (not is_image) and self._check_has_audio(clip_path) and keep_original_audio
            
            # Silence detection (bypassed to avoid dropping planned video frames)
            intervals = [(start_in, min(end_in, orig_duration))]

            # Normalization and ducking volume factors
            norm_gain = self._get_audio_normalization_gain(clip_path) if has_audio else 1.0
            if original_audio_volume is not None:
                duck_gain = original_audio_volume
            else:
                duck_gain = self.ORIGINAL_AUDIO_VOLUME if music_active else 1.0
            final_audio_gain = norm_gain * duck_gain

            # Horizontal crop centering using face_anchor_x (with Haar cascade fallback)
            face_x = face_anchor_x
            if face_anchor_x == 0.5:
                mid_time = (start_in + end_in) / 2
                frame_rgb = self._get_video_frame_at_time(clip_path, mid_time)
                if frame_rgb is not None:
                    face_center = detect_face_center(frame_rgb)
                    if face_center:
                        face_x = face_center[0]
                        logger.info(f"Smart Cropping Fallback: Haar face detected at x={face_x:.2f}")

            scale = max(target_w / clip_w, target_h / clip_h)
            new_w, new_h = int(clip_w * scale), int(clip_h * scale)
            
            crop_center_x = face_x * new_w
            x1 = max(0, min(new_w - target_w, int(crop_center_x - target_w / 2)))
            y1 = (new_h - target_h) // 2
            
            logger.info(f"Smart Cropping: Using anchor x={face_x:.2f}. Anchoring crop box horizontally to {x1}.")

            ffmpeg_inputs = [("-i", clip_path)]
            
            effect_input_idx = -1
            if effect_path and os.path.exists(effect_path):
                effect_input_idx = len(ffmpeg_inputs)
                ffmpeg_inputs.append(("-stream_loop -1 -i", effect_path))
                
            sticker_input_idx = -1
            if sticker_path and os.path.exists(sticker_path):
                sticker_input_idx = len(ffmpeg_inputs)
                if sticker_path.lower().endswith(".gif"):
                    ffmpeg_inputs.append(("-ignore_loop 0 -i", sticker_path))
                else:
                    ffmpeg_inputs.append(("-stream_loop -1 -i", sticker_path))



            # Build FFmpeg filters
            filter_complex_parts = []
            video_output_names = []
            audio_output_names = []
            
            use_custom_speed = bool(speed_preset or speed_keyframes or reverse)
            if speed_keyframes:
                from backend_ai.effects.motion import get_average_speed_linear
                avg_speed = get_average_speed_linear(speed_keyframes)
            elif speed_preset:
                from backend_ai.effects.motion import SPEED_PRESETS, get_average_speed_linear
                preset_keys = SPEED_PRESETS.get(speed_preset)
                avg_speed = get_average_speed_linear(preset_keys) if preset_keys else 1.0
            else:
                avg_speed = self.PACING_SPEED.get(pacing, 1.0)
                
            if avg_speed <= 0:
                avg_speed = 1.0

            # If not custom speed but avg_speed is not 1.0, unify it as keyframes
            if not use_custom_speed and avg_speed != 1.0:
                speed_keyframes = [(0.0, avg_speed), (1.0, avg_speed)]
                use_custom_speed = True

            speed = avg_speed

            # Pre-calculate output duration so it can be referenced in transparent canvas / overlay animations
            total_intervals_duration = sum(e - s for s, e in intervals) / speed
            output_duration = target_duration if (target_duration > 0 and target_duration < total_intervals_duration) else total_intervals_duration

            color_filter_str = ""
            if color_grade:
                from backend_ai.effects.color import ColorGradeParams, build_ffmpeg_color_filter
                if isinstance(color_grade, dict):
                    params = ColorGradeParams(**color_grade)
                else:
                    params = color_grade
                color_filter_str = build_ffmpeg_color_filter(params)

            clip_effect_str = ""
            if clip_effect and clip_effect.get("effect_type") and clip_effect.get("effect_type") != "none":
                eff_type = clip_effect.get("effect_type")
                params = clip_effect.get("parameters") or {}
                if eff_type == "blur":
                    max_blur_size = int(params.get("max_blur_size", 51))
                    if max_blur_size % 2 == 0:
                        max_blur_size = max(1, max_blur_size - 1)
                    radius = max(1, max_blur_size // 4)
                    clip_effect_str = f"boxblur=lr={radius}:lp=2"
                elif eff_type == "pixelate":
                    cell_size = int(params.get("max_cell_size", 32))
                    if cell_size <= 1:
                        cell_size = 32
                    clip_effect_str = f"scale=iw/{cell_size}:ih/{cell_size},scale={target_w}:{target_h}:flags=neighbor"
                elif eff_type == "vignette":
                    vignette_strength = float(params.get("vignette_strength", 0.5))
                    import math
                    angle = vignette_strength * (math.pi / 4.0)
                    clip_effect_str = f"vignette=angle={angle:.4f}"
                elif eff_type == "mirror":
                    direction = str(params.get("direction", "horizontal")).lower()
                    if direction == "vertical":
                        clip_effect_str = "vflip"
                    else:
                        clip_effect_str = "hflip"
                elif eff_type == "glitch":
                    clip_effect_str = "noise=alls=20:allf=t+u"
                elif eff_type == "light_leak":
                    clip_effect_str = "eq=brightness=0.1:contrast=1.1"
                
            for idx, (s, e) in enumerate(intervals):
                v_name = f"v{idx}"
                a_name = f"a{idx}"
                
                v_filters = []
                v_filters.append(f"trim=start={s}:end={e}")
                v_filters.append("setpts=PTS-STARTPTS")
                v_filters.append("fps=fps=30")
                
                if use_custom_speed:
                    from backend_ai.effects.motion import build_ffmpeg_speed_filter
                    v_speed, a_speed = build_ffmpeg_speed_filter(
                        duration=e - s,
                        keyframes=speed_keyframes,
                        preset=speed_preset,
                        reverse=reverse
                    )
                    v_filters.append(v_speed)
                    
                v_filters.append(f"scale={new_w}:{new_h}")
                v_filters.append(f"crop={target_w}:{target_h}:{x1}:{y1}")
                
                if stabilize_trf_path:
                    trf_path_escaped = stabilize_trf_path.replace("\\", "/").replace(":", "\\:")
                    v_filters.append(f"vidstabtransform=input={trf_path_escaped}:smoothing=15:optzoom=1")
                    
                if color_filter_str:
                    v_filters.append(color_filter_str)
                if clip_effect_str:
                    v_filters.append(clip_effect_str)

                filter_complex_parts.append(
                    f"[0:v]{','.join(v_filters)}[{v_name}]"
                )
                
                if use_custom_speed and a_speed != "copy":
                    if has_audio:
                        filter_complex_parts.append(
                            f"[0:a]atrim=start={s}:end={e},asetpts=PTS-STARTPTS,{a_speed}[{a_name}]"
                        )
                    else:
                        dur = (e - s) / speed
                        filter_complex_parts.append(
                            f"aevalsrc=0:d={dur:.3f},asetpts=PTS-STARTPTS[{a_name}]"
                        )
                else:
                    if has_audio:
                        filter_complex_parts.append(
                            f"[0:a]atrim=start={s}:end={e},asetpts=PTS-STARTPTS[{a_name}]"
                        )
                    else:
                        dur = e - s
                        filter_complex_parts.append(
                            f"aevalsrc=0:d={dur},asetpts=PTS-STARTPTS[{a_name}]"
                        )
                    
                video_output_names.append(f"[{v_name}]")
                audio_output_names.append(f"[{a_name}]")
                
            num_segments = len(intervals)
            concat_in = "".join(v + a for v, a in zip(video_output_names, audio_output_names))
            filter_complex_parts.append(
                f"{concat_in}concat=n={num_segments}:v=1:a=1[v_concat][a_concat]"
            )
            
            filter_complex_parts.append(
                f"[a_concat]volume={final_audio_gain}[a_final]"
            )
            
            video_proc_in = "[v_concat]"
            
            # Apply transitions (zoom_in / zoom_out)
            if transition == "zoom_in":
                filter_complex_parts.append(
                    f"{video_proc_in}zoompan=z='1+0.04*on/30':d=1:x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':s={target_w}x{target_h}:fps=30[v_zoom]"
                )
                video_proc_in = "[v_zoom]"
            elif transition == "zoom_out":
                filter_complex_parts.append(
                    f"{video_proc_in}zoompan=z='1.1-0.04*on/30':d=1:x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':s={target_w}x{target_h}:fps=30[v_zoom]"
                )
                video_proc_in = "[v_zoom]"
                
            # Apply text overlay
            if text_overlay:
                if dynamic_style:
                    style_cfg = dynamic_style.get("text_overlay_style") or dynamic_style
                else:
                    style_name = AGENTS_CONFIG.get("subtitle_agent", {}).get("caption_style", "hormozi")
                    style_cfg = AGENTS_CONFIG.get("caption_styles", {}).get(style_name, {})
                    
                font_name = style_cfg.get("font_name", "Arial")
                font_color = style_cfg.get("font_color", "white")
                font_size = style_cfg.get("font_size", 70)
                font_weight = style_cfg.get("font_weight", 700)
                outline_color = style_cfg.get("outline_color", "black")
                outline_width = style_cfg.get("outline_width", 2)
                
                # Check for style presets
                if text_preset:
                    from backend_ai.effects.text_presets import TEXT_PRESETS
                    preset_cfg = TEXT_PRESETS.get(text_preset, {})
                    font_name = preset_cfg.get("font_name", font_name)
                    font_color = preset_cfg.get("font_color", font_color)
                    font_size = preset_cfg.get("font_size", font_size)
                    outline_color = preset_cfg.get("outline_color", outline_color)
                    outline_width = preset_cfg.get("outline_width", outline_width)
                    if not text_animation:
                        text_animation = preset_cfg.get("default_animation", "none")
                
                if not text_animation:
                    text_animation = "none"

                if not dynamic_style and font_size < 50:
                    font_size = 70
                    
                if outline_color == "none":
                    outline_width = 0

                font_path = self._find_font(font_name, font_weight)
                escaped_text = self._escape_drawtext(text_overlay)
                font_path_escaped = font_path.replace("\\", "/").replace(":", "\\:")
                
                # Render text on a transparent 1080x1920 (target size) canvas first
                x_resting = "(w-text_w)/2"
                y_resting = "h*0.15"
                
                drawtext_parts = [
                    f"drawtext=fontfile='{font_path_escaped}'",
                    f"text='{escaped_text}'",
                    f"fontsize={font_size}",
                    f"fontcolor={font_color}",
                    f"x={x_resting}",
                    f"y={y_resting}"
                ]
                
                # Handle shadow option dynamically
                cfg_has_shadow = style_cfg.get("has_shadow", True)
                shadow_color = style_cfg.get("shadow_color", "none")
                shadow_width = style_cfg.get("shadow_width", 0)
                if cfg_has_shadow and shadow_color != "none" and shadow_width > 0:
                    drawtext_parts.append(f"shadowx={shadow_width}")
                    drawtext_parts.append(f"shadowy={shadow_width}")
                    drawtext_parts.append(f"shadowcolor={shadow_color}")

                if outline_width > 0:
                    drawtext_parts.append(f"borderw={outline_width}")
                    drawtext_parts.append(f"bordercolor={outline_color}")
                    
                text_layer_name = "text_layer"
                text_anim_layer_name = "text_anim_layer"
                
                # 1. Create transparent canvas + text drawing
                filter_complex_parts.append(
                    f"color=c=black@0:s={target_w}x{target_h}:d={output_duration},{':'.join(drawtext_parts)}[{text_layer_name}]"
                )
                
                # 2. Build text entrance/exit animations
                from backend_ai.effects.text_animation import build_ffmpeg_overlay_filters
                v_fade_filter, x_expr, y_expr = build_ffmpeg_overlay_filters(
                    duration=output_duration,
                    anim_type=text_animation,
                    x_resting="0",   # Placed correctly on transparent canvas, so relative resting offset is 0
                    y_resting="0"
                )
                
                if v_fade_filter != "copy":
                    filter_complex_parts.append(
                        f"[{text_layer_name}]{v_fade_filter}[{text_anim_layer_name}]"
                    )
                    text_layer_source = f"[{text_anim_layer_name}]"
                else:
                    text_layer_source = f"[{text_layer_name}]"
                    
                # 3. Composite the animated text layer onto the video
                filter_complex_parts.append(
                    f"{video_proc_in}{text_layer_source}overlay=x='{x_expr}':y='{y_expr}':shortest=1[v_text_applied]"
                )
                video_proc_in = "[v_text_applied]"
                
            # Apply visual effect loop overlay if present
            if effect_input_idx > 0:
                filter_complex_parts.append(
                    f"[{effect_input_idx}:v]scale={target_w}:{target_h},fps=fps=30[v_effect_scaled]"
                )
                filter_complex_parts.append(
                    f"{video_proc_in}[v_effect_scaled]blend=all_mode=screen:all_opacity=0.7[v_effect_applied]"
                )
                video_proc_in = "[v_effect_applied]"
                
            # Apply sticker overlay if present
            if sticker_input_idx > 0:
                sticker_w = int(target_w * 0.30)
                filter_complex_parts.append(
                    f"[{sticker_input_idx}:v]scale={sticker_w}:-1,fps=fps=30[v_sticker_scaled]"
                )
                pos_map = {
                    "center": ("(W-w)/2", "(H-h)/2"),
                    "top-left": ("50", "120"),
                    "top-right": ("W-w-50", "120"),
                    "bottom-left": ("50", "H-h-320"),
                    "bottom-right": ("W-w-50", "H-h-320"),
                    "bottom-center": ("(W-w)/2", "H-h-320"),
                }
                
                sticker_layer = "[v_sticker_scaled]"
                if sticker_animation and sticker_animation != "none":
                    from backend_ai.effects.text_animation import build_ffmpeg_overlay_filters
                    x_resting, y_resting = pos_map.get(sticker_position, pos_map["bottom-center"])
                    
                    v_fade_filter, x_expr, y_expr = build_ffmpeg_overlay_filters(
                        duration=output_duration,
                        anim_type=sticker_animation,
                        x_resting=x_resting,
                        y_resting=y_resting
                    )
                    
                    if v_fade_filter != "copy":
                        filter_complex_parts.append(
                            f"[v_sticker_scaled]{v_fade_filter}[v_sticker_animated]"
                        )
                        sticker_layer = "[v_sticker_animated]"
                else:
                    x_resting, y_resting = pos_map.get(sticker_position, pos_map["bottom-center"])
                    x_expr = x_resting
                    y_expr = y_resting
                    
                filter_complex_parts.append(
                    f"{video_proc_in}{sticker_layer}overlay=x='{x_expr}':y='{y_expr}':shortest=1[v_sticker_applied]"
                )
                video_proc_in = "[v_sticker_applied]"

            filter_complex_parts.append(
                f"{video_proc_in}copy[v_final]"
            )
            
            filter_complex_str = ";".join(filter_complex_parts)
            
            cmd = ["ffmpeg", "-y", "-nostdin"]
            for arg_prefix, path in ffmpeg_inputs:
                if arg_prefix == "-i":
                    cmd.extend(["-i", path])
                else:
                    cmd.extend(arg_prefix.split())
                    cmd.append(path)
                    
            cmd.extend([
                "-filter_complex", filter_complex_str,
                "-map", "[v_final]",
                "-map", "[a_final]",
                "-c:v", "libx264",
                "-pix_fmt", "yuv420p",
                "-c:a", "aac",
                "-ar", "44100",
                "-ac", "2",
                "-t", f"{output_duration:.3f}",
                temp_path
            ])
            
            logger.info(f"Running FFmpeg clip process command: {' '.join(cmd)}")
            try:
                result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, stdin=subprocess.DEVNULL, timeout=300)
            except subprocess.TimeoutExpired as e:
                logger.error(f"FFmpeg clip process timed out after 300 seconds for {clip_path}")
                raise RuntimeError(f"FFmpeg clip process timed out: {e}")

            if result.returncode != 0:
                logger.error(f"FFmpeg clip process failed for {clip_path}")
                logger.error(f"FFmpeg stderr: {result.stderr}")
                raise RuntimeError(f"FFmpeg clip process failed: {result.stderr}")
                
            return output_duration

        finally:
            if temp_kb and os.path.exists(temp_kb):
                try:
                    os.remove(temp_kb)
                except Exception as e:
                    logger.warning(f"Failed to remove temp_kb {temp_kb}: {e}")
            if temp_stabilized and os.path.exists(temp_stabilized):
                try:
                    os.remove(temp_stabilized)
                except Exception as e:
                    logger.warning(f"Failed to remove temp_stabilized {temp_stabilized}: {e}")

    def _build_ffmpeg_concat(
        self,
        clip_paths: list[str],
        clip_durations: list[float],
        clip_has_audio: list[bool],
        transitions: list[str],
        output_path: str,
        music_path: Optional[str] = None,
        music_start_offset: float = 0.0,
        tempo: float = 0.0,
        style: str = "cinematic",
        music_volumes: Optional[list[Optional[float]]] = None,
    ) -> None:
        """Assemble processed clips with FFmpeg's streaming filter graph."""
        if not clip_paths:
            raise RuntimeError("No processed clips were produced for FFmpeg assembly.")

        if not (len(clip_paths) == len(clip_durations) == len(transitions)):
            raise ValueError("FFmpeg assembly inputs must have matching lengths.")

        transition_map = {
            "crossfade": "fade",
            "fade": "fade",
            "dip_to_black": "fadeblack",
            "slide_left": "slideleft",
            "slide_right": "slideright",
        }
        temp_dir = tempfile.mkdtemp(prefix="ffmpeg_assemble_", dir=os.path.dirname(output_path))
        current_path = clip_paths[0]
        current_duration = float(clip_durations[0])

        # Calculate beat-synchronized transition duration (Task 35)
        if tempo and tempo > 0:
            beat_duration = 60.0 / tempo
            style_lower = style.lower() if style else ""
            if any(s in style_lower for s in ["fast", "energy", "ramp", "action", "travel"]):
                beat_fraction = 0.5
            else:
                beat_fraction = 1.0
            sync_fade_duration = beat_duration * beat_fraction
            # Clamp to a natural range
            sync_fade_duration = max(0.1, min(1.0, sync_fade_duration))
            logger.info(
                f"Beat sync transition: tempo={tempo} BPM, beat_dur={beat_duration:.3f}s, "
                f"fraction={beat_fraction}, sync_dur={sync_fade_duration:.3f}s"
            )
        else:
            sync_fade_duration = self.DEFAULT_FADE_DURATION

        try:
            for idx in range(1, len(clip_paths)):
                transition = (transitions[idx] or "none").lower()
                next_path = clip_paths[idx]
                next_duration = float(clip_durations[idx])
                stage_path = os.path.join(temp_dir, f"stage_{idx:03d}.mp4")

                current_input = ffmpeg.input(current_path)
                next_input = ffmpeg.input(next_path)
                target_fps = 30
                cur_video_norm = current_input.video.filter('fps', fps=target_fps)
                next_video_norm = next_input.video.filter('fps', fps=target_fps)

                if transition in transition_map:
                    fade_dur = min(sync_fade_duration, current_duration / 2, next_duration / 2)
                    if fade_dur > 0:
                        offset = max(0.0, current_duration - fade_dur)
                        video_stream = ffmpeg.filter(
                            [cur_video_norm, next_video_norm],
                            "xfade",
                            transition=transition_map[transition],
                            duration=fade_dur,
                            offset=offset,
                        )

                        if current_input.audio is not None and next_input.audio is not None:
                            cur_audio_norm = current_input.audio.filter('aformat', sample_rates=44100, channel_layouts='stereo')
                            next_audio_norm = next_input.audio.filter('aformat', sample_rates=44100, channel_layouts='stereo')
                            audio_stream = ffmpeg.filter(
                                [cur_audio_norm, next_audio_norm],
                                "acrossfade",
                                d=fade_dur,
                            )
                            stream = ffmpeg.output(
                                video_stream,
                                audio_stream,
                                stage_path,
                                vcodec="libx264",
                                acodec="aac",
                                pix_fmt="yuv420p",
                                movflags="+faststart",
                                nostdin=None,
                                ar="44100",
                                ac="2"
                            )
                        else:
                            stream = ffmpeg.output(
                                video_stream,
                                stage_path,
                                vcodec="libx264",
                                pix_fmt="yuv420p",
                                movflags="+faststart",
                                nostdin=None,
                            )

                        try:
                            stream.overwrite_output().run(capture_stdout=True, capture_stderr=True)
                        except ffmpeg.Error as exc:
                            stderr = exc.stderr.decode("utf-8", errors="replace") if isinstance(exc.stderr, bytes) else str(exc.stderr)
                            raise RuntimeError(f"FFmpeg transition assembly failed: {stderr[-2000:]}") from exc

                        current_path = stage_path
                        current_duration = current_duration + next_duration - fade_dur
                        continue

                if current_input.audio is not None and next_input.audio is not None:
                    cur_audio_norm = current_input.audio.filter('aformat', sample_rates=44100, channel_layouts='stereo')
                    next_audio_norm = next_input.audio.filter('aformat', sample_rates=44100, channel_layouts='stereo')
                    concat_node = ffmpeg.concat(
                        cur_video_norm,
                        cur_audio_norm,
                        next_video_norm,
                        next_audio_norm,
                        n=2,
                        v=1,
                        a=1,
                    )
                    video_stream = concat_node.node.stream("v")
                    audio_stream = concat_node.node.stream("a")
                    stream = ffmpeg.output(
                        video_stream,
                        audio_stream,
                        stage_path,
                        vcodec="libx264",
                        acodec="aac",
                        pix_fmt="yuv420p",
                        movflags="+faststart",
                        nostdin=None,
                        ar="44100",
                        ac="2"
                    )
                else:
                    concat_node = ffmpeg.concat(
                        cur_video_norm,
                        next_video_norm,
                        n=2,
                        v=1,
                        a=0,
                    )
                    stream = ffmpeg.output(
                        concat_node.node.stream("v"),
                        stage_path,
                        vcodec="libx264",
                        pix_fmt="yuv420p",
                        movflags="+faststart",
                        nostdin=None,
                    )

                try:
                    stream.overwrite_output().run(capture_stdout=True, capture_stderr=True)
                except ffmpeg.Error as exc:
                    stderr = exc.stderr.decode("utf-8", errors="replace") if isinstance(exc.stderr, bytes) else str(exc.stderr)
                    raise RuntimeError(f"FFmpeg assembly failed: {stderr[-2000:]}") from exc

                current_path = stage_path
                current_duration += next_duration

            output_args = {
                "vcodec": "libx264",
                "pix_fmt": "yuv420p",
                "movflags": "+faststart",
                "nostdin": None,
                "ar": "44100",
                "ac": "2"
            }

            # Calculate dynamic audio ducking intervals (Task 34)
            active_intervals = []
            accumulated = 0.0
            for idx in range(len(clip_paths)):
                dur = clip_durations[idx]
                has_aud = clip_has_audio[idx]
                mus_vol = music_volumes[idx] if (music_volumes and idx < len(music_volumes)) else None
                
                # Check transition overlap for correct timing
                transition_term = (transitions[idx] or "none").lower()
                fade_overlap = 0.0
                if idx > 0 and transition_term in transition_map:
                    prev_dur = clip_durations[idx - 1]
                    fade_overlap = min(sync_fade_duration, prev_dur / 2, dur / 2)
                
                if idx > 0:
                    accumulated -= fade_overlap
                    
                # Determine music volume for this segment
                if mus_vol is None:
                    if has_aud:
                        mus_vol = self.MUSIC_DUCKED_VOLUME
                    else:
                        mus_vol = self.MUSIC_VOLUME
                
                active_intervals.append((accumulated, accumulated + dur, mus_vol))
                accumulated += dur

            final_input = ffmpeg.input(current_path)
            if music_path and os.path.exists(music_path):
                music_input = ffmpeg.input(music_path, stream_loop=-1)
                music_audio = music_input.audio.filter(
                    "atrim",
                    start=max(0.0, music_start_offset),
                    duration=current_duration,
                ).filter("asetpts", "PTS-STARTPTS")

                # Apply dynamic audio ducking (Task 34)
                if active_intervals:
                    # Build time-varying volume envelope expression
                    volume_expr = f"{self.MUSIC_VOLUME}"
                    for start, end, vol in reversed(active_intervals):
                        volume_expr = f"if(between(t,{start:.3f},{end:.3f}),{vol:.3f},{volume_expr})"
                    logger.info(f"Dynamic Audio Ducking active intervals count: {len(active_intervals)}")
                    logger.debug(f"Volume filter expression: {volume_expr}")
                else:
                    volume_expr = f"{self.MUSIC_VOLUME}"
                    logger.info("No active audio clips detected. Background music volume constant.")

                music_audio = music_audio.filter("volume", volume_expr, eval="frame")

                fade_out_start = max(0.0, current_duration - 1.5)
                music_audio = music_audio.filter("afade", t="out", st=fade_out_start, d=1.5)

                if final_input.audio is not None:
                    cur_audio_norm = final_input.audio.filter('aformat', sample_rates=44100, channel_layouts='stereo')
                    music_audio_norm = music_audio.filter('aformat', sample_rates=44100, channel_layouts='stereo')
                    mixed_audio = ffmpeg.filter(
                        [cur_audio_norm, music_audio_norm],
                        "amix",
                        inputs=2,
                        duration="first",
                        dropout_transition=0,
                        normalize=0,
                    )
                else:
                    mixed_audio = music_audio.filter('aformat', sample_rates=44100, channel_layouts='stereo')

                stream = ffmpeg.output(final_input.video, mixed_audio, output_path, acodec="aac", **output_args)
            elif final_input.audio is not None:
                cur_audio_norm = final_input.audio.filter('aformat', sample_rates=44100, channel_layouts='stereo')
                stream = ffmpeg.output(final_input.video, cur_audio_norm, output_path, acodec="aac", **output_args)
            else:
                stream = ffmpeg.output(final_input.video, output_path, **output_args)

            try:
                stream.overwrite_output().run(capture_stdout=True, capture_stderr=True)
            except ffmpeg.Error as exc:
                stderr = exc.stderr.decode("utf-8", errors="replace") if isinstance(exc.stderr, bytes) else str(exc.stderr)
                raise RuntimeError(f"FFmpeg assembly failed: {stderr[-2000:]}") from exc
        finally:
            # shutil.rmtree(temp_dir, ignore_errors=True)
            pass

    def _enforce_final_duration(self, file_path: str, target_duration: float) -> None:
        if target_duration <= 0:
            return
            
        cap = cv2.VideoCapture(file_path)
        if not cap.isOpened():
            return
        fps = cap.get(cv2.CAP_PROP_FPS)
        frame_count = cap.get(cv2.CAP_PROP_FRAME_COUNT)
        actual_duration = frame_count / fps if fps > 0 else 0.0
        cap.release()
        
        if abs(actual_duration - target_duration) < 0.1:
            return
            
        temp_output = file_path.replace(".mp4", "_duration_enforced.mp4")
        if actual_duration > target_duration:
            logger.info(f"Trimming final video: {actual_duration:.2f}s -> target {target_duration:.2f}s")
            cmd = [
                "ffmpeg", "-y", "-nostdin",
                "-i", file_path,
                "-t", f"{target_duration:.3f}",
                "-c", "copy",
                temp_output
            ]
            subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.DEVNULL)
            os.replace(temp_output, file_path)
        else:
            pad_duration = target_duration - actual_duration
            logger.info(f"Padding final video: {actual_duration:.2f}s -> target {target_duration:.2f}s (padding of {pad_duration:.2f}s)")
            
            black_temp = tempfile.mktemp(suffix=".mp4", dir=os.path.dirname(file_path))
            cmd_black = [
                "ffmpeg", "-y", "-nostdin",
                "-f", "lavfi", "-i", f"color=c=black:s={self.target_w}x{self.target_h}:r=30:d={pad_duration:.3f}",
                "-f", "lavfi", "-i", f"anullsrc=channel_layout=stereo:sample_rate=44100:d={pad_duration:.3f}",
                "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac",
                black_temp
            ]
            subprocess.run(cmd_black, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.DEVNULL)
            
            concat_list = tempfile.mktemp(suffix=".txt", dir=os.path.dirname(file_path))
            with open(concat_list, "w") as f:
                p1 = os.path.abspath(file_path).replace("\\", "/")
                p2 = os.path.abspath(black_temp).replace("\\", "/")
                f.write(f"file '{p1}'\n")
                f.write(f"file '{p2}'\n")
                
            cmd_concat = [
                "ffmpeg", "-y", "-nostdin",
                "-f", "concat",
                "-safe", "0",
                "-i", concat_list,
                "-c", "copy",
                temp_output
            ]
            subprocess.run(cmd_concat, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.DEVNULL)
            
            os.remove(concat_list)
            os.remove(black_temp)
            os.replace(temp_output, file_path)

    def _cleanup_temp_files(self, temp_files: list[str], temp_dir: Optional[str] = None) -> None:
        for path in temp_files:
            if not path:
                continue
            try:
                if os.path.exists(path):
                    os.unlink(path)
            except Exception as e:
                logger.warning(f"Failed to delete temp file {path}: {e}")

        if temp_dir and os.path.isdir(temp_dir):
            try:
                shutil.rmtree(temp_dir, ignore_errors=True)
            except Exception:
                pass

    def render(
        self,
        edl: Dict[str, Any],
        music_path: Optional[str] = None,
        output_filename: str = "shortify_output.mp4",
        aspect_ratio: str = "9:16",
        rhythm_data: Optional[Dict[str, Any]] = None,
        clip_scores: Optional[Dict[str, Any]] = None,
        dynamic_style: Optional[Dict[str, Any]] = None,
        audio_ducking: bool = True
    ) -> str:
        """
        Renders the final video from an EDL produced by CreativeDirector.
        """
        # --- NEW RENDER PLANNER COMPILATION ENGINE INTEGRATION ---
        try:
            from backend_ai.schemas.edl import EDLDocument, convert_edl_to_timeline_ir
            from backend_ai.services.render_planner import RenderPlanner
            from backend_ai.services.validation_resolver import ValidationConflictResolver
            
            logger.info("VideoEditor: Invoking new compile-render complex filter graph planner.")
            edl_doc = EDLDocument.model_validate(edl)
            timeline_ir = convert_edl_to_timeline_ir(edl_doc)
            
            # Resolve conflicts/boundaries first
            resolver = ValidationConflictResolver()
            resolver.resolve_conflicts(timeline_ir)
            
            # Compile to a single optimized command
            planner = RenderPlanner(clips_dir=self.clips_dir, output_dir=self.output_dir)
            cmd = planner.compile_timeline_to_ffmpeg_cmd(
                timeline=timeline_ir,
                output_filename=output_filename,
                aspect_ratio=aspect_ratio,
                clip_scores=clip_scores,
                audio_ducking=audio_ducking,
                music_path=music_path
            )
            
            logger.info(f"VideoEditor: Executing compiled rendering command: {' '.join(cmd)}")
            result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, check=True, stdin=subprocess.DEVNULL)
            
            output_path = os.path.join(self.output_dir, output_filename)
            self._enforce_final_duration(output_path, float(timeline_ir.total_duration))
            return output_path
            
        except Exception as e:
            logger.warning(f"Compiled render engine failed, falling back to legacy procedural render: {e}")
        # ---------------------------------------------------------

        self.skipped_clips = []
        try:
            validated_edl = validate_edl(edl, self.clips_dir)
            edl = validated_edl.model_dump(mode="json")
        except Exception as exc:
            if os.getenv("EDL_VALIDATION_FAIL", "stop").strip().lower() == "pass":
                logger.warning(f"EDL validation failed in rendering phase: {exc}. EDL_VALIDATION_FAIL is 'pass', so bypassing validation check.")
            else:
                raise exc

        timeline = edl.get("timeline", [])
        if not timeline:
            raise ValueError("EDL timeline is empty. Nothing to render.")

        timeline.sort(key=lambda x: float(x.get("timeline_start", 0.0)))

        dimensions_map = {
            "9:16": (1080, 1920),
            "16:9": (1920, 1080),
            "1:1": (1080, 1080),
        }
        self.target_w, self.target_h = dimensions_map.get(aspect_ratio, (1080, 1920))

        title = edl.get("title", "Untitled")
        logger.info(f"Rendering '{title}' | aspect={aspect_ratio} | dims={self.target_w}x{self.target_h} | segments={len(timeline)}")

        processed_temp_files = []
        processed_durations = []
        transitions = []
        processed_has_audio = []
        original_music_volumes = []
        temp_dir = tempfile.mkdtemp(prefix="video_editor_", dir=self.output_dir)
        
        beat_times = rhythm_data.get("beat_times", []) if rhythm_data else []
        accumulated_time = 0.0

        output_path = os.path.join(self.output_dir, output_filename)

        try:
            for i, item in enumerate(timeline):
                clip_name = item.get("clip_name", "")
                start_in = float(item.get("start_in_clip", 0.0))
                end_in = float(item.get("end_in_clip", 0.0))
                tl_start = float(item.get("timeline_start", 0.0))
                tl_end = float(item.get("timeline_end", end_in - start_in))
                transition = item.get("transition", "none").lower()
                details = item.get("details", {})
                pacing = details.get("pacing_style", "jump-cut").lower()

                # Snapping to beats
                raw_duration = tl_end - tl_start
                target_duration = raw_duration

                if beat_times:
                    raw_tl_end = accumulated_time + raw_duration
                    nearest_beat = min(beat_times, key=lambda b: abs(b - raw_tl_end))
                    tolerance = float(self.beat_snap_tolerances.get(pacing, self.default_beat_snap_tolerance))
                    if abs(nearest_beat - raw_tl_end) <= tolerance:
                        target_duration = max(0.1, nearest_beat - accumulated_time)
                        logger.info(
                            f"Beat sync: snapping clip end {raw_tl_end:.2f}s -> beat {nearest_beat:.2f}s "
                            f"(dur {raw_duration:.2f}s -> {target_duration:.2f}s, tolerance={tolerance}s)"
                        )

                accumulated_time += target_duration

                # Virtual clip extraction
                virtual_start = 0.0
                virtual_end = None
                source_filename = clip_name

                if ":" in clip_name:
                    parts = clip_name.split(":", 2)
                    if len(parts) == 3:
                        try:
                            source_filename = parts[0]
                            virtual_start = float(parts[1])
                            virtual_end = float(parts[2])
                        except ValueError:
                            pass

                clip_path = os.path.join(self.clips_dir, source_filename)
                if not os.path.exists(clip_path):
                    logger.warning(f"Clip not found, skipping: {clip_name}")
                    self.skipped_clips.append(clip_name)
                    continue

                ext = os.path.splitext(clip_path)[1].lower()
                is_image = ext in self.IMAGE_EXTENSIONS

                # Set subclip bounds
                if is_image:
                    actual_start = 0.0
                    actual_end = target_duration
                else:
                    if virtual_end is not None:
                        actual_start = virtual_start + start_in
                        actual_end = min(virtual_start + end_in, virtual_end)
                    else:
                        actual_start = start_in
                        actual_end = end_in

                temp_clip_path = os.path.join(temp_dir, f"clip_{len(processed_temp_files):03d}.mp4")
                
                try:
                    logger.info(f"Processing clip: {clip_name} -> {temp_clip_path}")
                    
                    face_anchor_x = 0.5
                    if clip_scores and source_filename in clip_scores:
                        face_anchor_x = clip_scores[source_filename].get("face_anchor_x", 0.5)

                    keep_aud = False if audio_ducking else details.get("keep_original_audio", True)
                    has_aud = (not is_image) and self._check_has_audio(clip_path) and keep_aud

                    ducking_params = item.get("audio_ducking") or {}
                    orig_audio_vol = 0.0 if audio_ducking else ducking_params.get("original_audio_volume")
                    music_vol = self.MUSIC_VOLUME if audio_ducking else ducking_params.get("music_volume_during_segment")

                    processed_dur = self._process_single_clip(
                        clip_path=clip_path,
                        is_image=is_image,
                        start_in=actual_start,
                        end_in=actual_end,
                        target_duration=target_duration,
                        transition=transition,
                        text_overlay=item.get("text_overlay", "").strip(),
                        pacing=pacing,
                        music_active=bool(music_path and os.path.exists(music_path)),
                        temp_path=temp_clip_path,
                        face_anchor_x=face_anchor_x,
                        keep_original_audio=keep_aud,
                        dynamic_style=dynamic_style,
                        sticker_path=item.get("sticker_path"),
                        sticker_position=item.get("sticker_position", "bottom-center"),
                        effect_path=item.get("effect_path"),
                        color_grade=item.get("color_grade") or edl.get("global_color_grade"),
                        clip_effect=item.get("clip_effect"),
                        speed_preset=item.get("speed_preset"),
                        speed_keyframes=item.get("speed_keyframes"),
                        reverse=item.get("reverse", False),
                        stabilize=item.get("stabilize", False),
                        stabilize_strength=item.get("stabilize_strength", 0.5),
                        text_preset=item.get("text_preset"),
                        text_animation=item.get("text_animation"),
                        sticker_animation=item.get("sticker_animation"),
                        original_audio_volume=orig_audio_vol
                    )
                    
                    processed_temp_files.append(temp_clip_path)
                    processed_durations.append(processed_dur)
                    transitions.append(transition)
                    processed_has_audio.append(has_aud)
                    original_music_volumes.append(music_vol)

                    media_type_label = "photo" if is_image else "video"
                    logger.info(
                        f"[{i+1}/{len(timeline)}] [{media_type_label}] {clip_name} | "
                        f"dur={processed_dur:.2f}s | transition={transition} | pacing={pacing}"
                    )
                except Exception as e:
                    logger.error(f"Failed to process clip {clip_name} at index {i}: {e}", exc_info=True)
                    self.skipped_clips.append(clip_name)
                    continue

            if not processed_temp_files:
                raise RuntimeError("No valid clips were processed. Check clips directory and EDL.")

            # Second Pass: Bake spatial-reveal transitions
            from backend_ai.effects.spatial_transitions import create_spatial_transition

            SPATIAL_TRANSITIONS = {
                "wipe_left", "wipe_right", "wipe_up", "wipe_down",
                "wipe_diagonal_tl", "wipe_diagonal_tr", "wipe_diagonal_bl", "wipe_diagonal_br",
                "split_horizontal", "split_vertical", "clock_wipe",
                "iris", "iris_circle", "diamond", "heart", 
                "blinds_horizontal", "blinds_vertical", "checkerboard",
                "glitch", "pixelate", "spin", "ripple", "blur", "light_leak",
                "slide_left", "slide_right", "slide_up", "slide_down", "slide_push"
            }

            # Determine sync fade duration based on rhythm_data tempo
            if rhythm_data and rhythm_data.get("tempo", 0.0) > 0:
                beat_duration = 60.0 / rhythm_data["tempo"]
                style_lower = edl.get("style", "cinematic").lower()
                if any(s in style_lower for s in ["fast", "energy", "ramp", "action", "travel"]):
                    beat_fraction = 0.5
                else:
                    beat_fraction = 1.0
                sync_fade_duration = beat_duration * beat_fraction
                sync_fade_duration = max(0.1, min(1.0, sync_fade_duration))
            else:
                sync_fade_duration = self.DEFAULT_FADE_DURATION

            i = 0
            i = 0
            baked_paths = []
            baked_durations = []
            baked_transitions = []
            baked_has_audio = []
            baked_music_volumes = []

            # Start with the first clip
            current_path = processed_temp_files[0]
            current_duration = processed_durations[0]
            current_has_audio = processed_has_audio[0]
            current_music_volume = original_music_volumes[0]

            while i < len(processed_temp_files) - 1:
                next_transition = (transitions[i + 1] or "none").lower()

                if next_transition in SPATIAL_TRANSITIONS:
                    next_path = processed_temp_files[i + 1]
                    next_duration = processed_durations[i + 1]
                    next_has_audio = processed_has_audio[i + 1]
                    next_music_volume = original_music_volumes[i + 1]
                    next_params = timeline[i + 1].get("transition_params") or {}

                    fade_dur = min(sync_fade_duration, current_duration / 2, next_duration / 2)
                    if fade_dur > 0.05:
                        logger.info(f"Baking spatial transition '{next_transition}' between clip {i} and {i+1} with duration {fade_dur:.3f}s")

                        # Generate temp file paths
                        trimmed_a_path = os.path.join(temp_dir, f"clip_{i}_trimmed_end.mp4")
                        trans_path = os.path.join(temp_dir, f"trans_{i}_{i+1}.mp4")
                        trimmed_b_path = os.path.join(temp_dir, f"clip_{i+1}_trimmed_start.mp4")

                        try:
                            # Trim A (keep [0, current_duration - fade_dur])
                            dur_a_trimmed = current_duration - fade_dur
                            cmd_trim_a = [
                                "ffmpeg", "-y", "-nostdin",
                                "-i", current_path,
                                "-t", f"{dur_a_trimmed:.3f}",
                                "-c:v", "libx264", "-pix_fmt", "yuv420p",
                                "-c:a", "aac", trimmed_a_path
                            ]
                            subprocess.run(cmd_trim_a, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True, timeout=90, stdin=subprocess.DEVNULL)

                            # Trim B (keep [fade_dur, next_duration])
                            dur_b_trimmed = next_duration - fade_dur
                            cmd_trim_b = [
                                "ffmpeg", "-y", "-nostdin",
                                "-i", next_path,
                                "-ss", f"{fade_dur:.3f}",
                                "-c:v", "libx264", "-pix_fmt", "yuv420p",
                                "-c:a", "aac", trimmed_b_path
                            ]
                            subprocess.run(cmd_trim_b, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True, timeout=90, stdin=subprocess.DEVNULL)

                            # Create spatial transition video in python
                            create_spatial_transition(
                                clip_a_path=current_path,
                                clip_b_path=next_path,
                                transition_name=next_transition,
                                duration=fade_dur,
                                output_path=trans_path,
                                fps=30,
                                frame_size=(self.target_h, self.target_w),
                                transition_params=next_params
                            )

                            # Append trimmed A
                            baked_paths.append(trimmed_a_path)
                            baked_durations.append(dur_a_trimmed)
                            baked_transitions.append("none")
                            baked_has_audio.append(current_has_audio)
                            baked_music_volumes.append(current_music_volume)

                            # Append baked transition
                            baked_paths.append(trans_path)
                            baked_durations.append(fade_dur)
                            baked_transitions.append("none")
                            baked_has_audio.append(current_has_audio or next_has_audio)
                            # Transition volume is average of the two
                            avg_vol = None
                            if current_music_volume is not None and next_music_volume is not None:
                                avg_vol = (current_music_volume + next_music_volume) / 2
                            elif current_music_volume is not None:
                                avg_vol = current_music_volume
                            elif next_music_volume is not None:
                                avg_vol = next_music_volume
                            baked_music_volumes.append(avg_vol)

                            # Set trimmed B as current clip for next iteration
                            current_path = trimmed_b_path
                            current_duration = dur_b_trimmed
                            current_has_audio = next_has_audio
                            current_music_volume = next_music_volume

                            # Mark transition as none for the next step
                            transitions[i + 1] = "none"

                            i += 1
                            continue
                        except Exception as e:
                            logger.error(f"Failed to bake spatial transition '{next_transition}' between clip {i} and {i+1}: {e}")
                            # Fallback to normal concatenation
                            pass

                # If no spatial transition or baking failed, append current clip as is
                baked_paths.append(current_path)
                baked_durations.append(current_duration)
                baked_transitions.append(transitions[i])
                baked_has_audio.append(current_has_audio)
                baked_music_volumes.append(current_music_volume)

                # Advance to next
                i += 1
                current_path = processed_temp_files[i]
                current_duration = processed_durations[i]
                current_has_audio = processed_has_audio[i]
                current_music_volume = original_music_volumes[i]

            # Append the final remaining clip
            baked_paths.append(current_path)
            baked_durations.append(current_duration)
            baked_transitions.append(transitions[-1])
            baked_has_audio.append(current_has_audio)
            baked_music_volumes.append(current_music_volume)

            processed_temp_files = baked_paths
            processed_durations = baked_durations
            transitions = baked_transitions
            processed_has_audio = baked_has_audio
            original_music_volumes = baked_music_volumes

            self._build_ffmpeg_concat(
                clip_paths=processed_temp_files,
                clip_durations=processed_durations,
                clip_has_audio=processed_has_audio,
                transitions=transitions,
                output_path=output_path,
                music_path=music_path,
                music_start_offset=float(edl.get("music_start_offset", 0.0)),
                tempo=rhythm_data.get("tempo", 0.0) if rhythm_data else 0.0,
                style=edl.get("style", "cinematic"),
                music_volumes=original_music_volumes,
            )

            # Enforce exact target duration (trim/pad final video)
            target_duration = float(edl.get("total_duration", 0.0))
            if target_duration > 0:
                self._enforce_final_duration(output_path, target_duration)

            logger.info(f"Render complete! Output: {output_path}")
            return output_path
        finally:
            self._cleanup_temp_files(processed_temp_files, temp_dir=temp_dir)


if __name__ == "__main__":
    logger.info("VideoEditor module loaded successfully.")
