import json
import os
import sys

# Add project root to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from backend_ai.services.editor_service import VideoEditor

def test_editor():
    print("--- Starting Phase 5: Video Editor Test ---")

    # 1. Load the EDL generated by Phase 4
    edl_path = "edl_output.json"
    if not os.path.exists(edl_path):
        print(f"Error: {edl_path} not found. Run tests/test_director.py first.")
        return

    with open(edl_path, "r") as f:
        edl = json.load(f)

    print(f"Loaded EDL: '{edl.get('title')}' with {len(edl.get('timeline', []))} segments.")

    # 2. Check for source clips
    clips_dir = "testing_data/Videos"
    if not os.path.exists(clips_dir):
        print(f"Error: Clips directory not found: {clips_dir}")
        return

    # 3. Optional: use an audio track (from rhythm test if it exists)
    music_path = None
    potential_music = "testing_data/Music/mixkit-crickets-and-insects-in-the-wild-ambience-39.wav"
    if os.path.exists(potential_music):
        music_path = potential_music
        print(f"Music track found: {music_path}")
    else:
        print("No music track found, rendering without background music.")

    # 4. Initialize editor and render
    try:
        editor = VideoEditor(
            clips_dir=clips_dir,
            output_dir="data/exports"
        )
        output = editor.render(
            edl=edl,
            music_path=music_path,
            output_filename="shortify_reel.mp4"
        )
        print(f"\nSuccess! Final video saved to: {output}")
    except Exception as e:
        import traceback
        print(f"An error occurred during rendering: {e}")
        traceback.print_exc()


if __name__ == "__main__":
    test_editor()
