import os
import json
import logging
from typing import List, Dict, Any, Optional
from backend_ai.core.api_utils import get_gemini_client
from dotenv import load_dotenv
from backend_ai.core.config_loader import AGENTS_CONFIG
from backend_ai.core.api_utils import rate_limit_guard

load_dotenv()
logger = logging.getLogger("agents.inspector")

INSPECTOR_JSON_SCHEMA = {
    "type": "object",
    "properties": {
        "verdict": {
            "type": "string",
            "enum": ["PASS", "REVISE"]
        },
        "feedback": {"type": "string"},
        "refinements": {
            "type": "object",
            "additionalProperties": True
        }
    },
    "required": ["verdict", "feedback"],
    "additionalProperties": False
}

class EditingInspector:
    def __init__(self):
        config = AGENTS_CONFIG.get("editing_inspector", {})
        self.gemini_client = get_gemini_client()
        self.model_id = config.get("model", "gemini-2.5-flash")
        self.fallback_models = config.get("fallback_models", ["gemini-2.5-pro", "gemini-1.5-pro", "gemini-1.5-flash"])

    def _call_gemini(self, model_id: str, messages: List[Dict[str, str]]) -> str:
        if not self.gemini_client:
            raise RuntimeError("Gemini client unavailable")
        
        system_instructions = ""
        user_content = ""
        for msg in messages:
            if msg["role"] == "system":
                system_instructions += msg["content"] + "\n"
            elif msg["role"] == "user":
                user_content += msg["content"] + "\n"

        from google.genai import types
        response = self.gemini_client.models.generate_content(
            model=model_id,
            contents=user_content,
            config=types.GenerateContentConfig(
                system_instruction=system_instructions,
                response_mime_type="application/json"
            )
        )
        return response.text

    @rate_limit_guard(max_retries=5)
    def review_timeline(
        self,
        user_prompt: str,
        timeline_ir: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Reviews a generated multi-track timeline IR against the creative brief.
        Returns a dict containing 'verdict' (PASS | REVISE) and 'feedback'.
        """
        logger.info("EditingInspector: Starting timeline review...")
        
        system_prompt = """
        You are a top-tier Professional Editing Inspector for video highlight reels (TikTok, Reels, Shorts).
        Your job is to strictly review the draft timeline IR generated by the creative director planner and check for editing violations, storytelling logic errors, and styling inconsistencies against the user brief/prompt.
        
        STYLING & COMPLIANCE RULES:
        1. HOOK COMPLIANCE: The video must start with a hook clip (duration of the first clip is 1.5s to 3.0s). If the first clip is too long, too short, or is not flagged as is_hook, highlight it.
        2. VIDEO CONTINUITY: Check that timeline start times are sorted chronologically and do not overlap.
        3. DURATION ALIGNMENT: Check that total timeline duration matches target duration.
        4. PACING GRAMMAR: Check that pacing style makes sense for the video style. Slow cinematic videos should not have rapid jump cuts, and dynamic gym/workout videos should not have flat long clips.
        5. OVERLAY BLEND: Overlays (smoke, light leak, film grain) must fit the context of the prompt (e.g. smoke overlay is appropriate for scary/noir, light leak is appropriate for warm travel, but neither should be overused on every single clip).
        6. SOUND DESIGN: Verify that sound design alerts (e.g. whoosh SFX) align with visual transition clips and are not random.
        
        OUTPUT FORMAT:
        You must return a raw JSON object with this structure:
        {
          "verdict": "PASS" | "REVISE",
          "feedback": "Detailed explanation of what needs to be changed if REVISE, or constructive notes if PASS. List specific clip IDs or index values.",
          "refinements": {
            // Optional minor structural improvements you can suggest directly (e.g. adjustments to layers, volume ducking, font sizes, transitions)
          }
        }
        """

        user_message = f"User Brief/Prompt: {user_prompt}\n\nDraft Timeline IR: {json.dumps(timeline_ir, indent=2)}"
        
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message}
        ]

        all_models = [self.model_id] + self.fallback_models
        last_error = None

        for model_id in all_models:
            try:
                logger.info(f"EditingInspector: Calling Gemini model: {model_id}")
                raw_response = self._call_gemini(model_id, messages)
                parsed = json.loads(raw_response)
                
                # Simple validation of output properties
                verdict = parsed.get("verdict", "PASS")
                feedback = parsed.get("feedback", "Looks good.")
                
                return {
                    "verdict": verdict,
                    "feedback": feedback,
                    "refinements": parsed.get("refinements", {})
                }
            except Exception as e:
                last_error = e
                logger.warning(f"EditingInspector: Gemini model '{model_id}' failed: {e}")

        logger.warning(f"EditingInspector: All models failed. Falling back to heuristic PASS. Error: {last_error}")
        return {
            "verdict": "PASS",
            "feedback": f"Heuristic pass due to model failure: {last_error}",
            "refinements": {}
        }
